using UnityEngine;
using System.Collections;


/// <summary>
/// notice:
/// 
/// 
/// MVC框架间传递事件用到的事件字段
/// model,module,controller的事件字段必须满足以下格式
/// MVC模块名_业务层模块名_具体派发内容(例如: MODULE_GAME_PAUSE , CMD_COMMERCIAL_GAIN_REWARD , MODEL_COMMERCIAL_ADD_CITY_DATA)
/// 
/// 
/// </summary>
public class MessageConst
{
    public const string TO_GUIDE_CARD_LEVELUP_RESET = "TO_GUIDE_CARD_LEVELUP_RESET";
    public const string TO_GUIDE_ACHIEVEMENT_RESET = "TO_GUIDE_ACHIEVEMENT_RESET";
    public const string TO_GUIDE_ACHIEVEMENT_NEXT_STEP = "TO_GUIDE_ACHIEVEMENT_NEXT_STEP";
    
    public const string MODULE_BATTLE_SHOW_FAIL = "MODULE_BATTLE_SHOW_FAIL";
    
    public const string MODULE_MAIN_NEXTCHAPTER = "MODULE_MAIN_NEXTCHAPTER";
    
    public const string MODULE_MUSICRHYRHM_BACK = "MODULE_MUSICRHYRHM_BACK";

    /// <summary>
    /// 练习室开始音游
    /// </summary>
    public const string MODULE_TRAININGROOM_ENTRY_GAME  = "MODULE_TRAININGROOM_ENTRY_GAME";


    public const string CMD_UPDATE_START_DOWNLOAD_HOTFIX_FILE = "CMD_UPDATE_START_DOWNLOAD_HOTFIX_FILE";
    public const string CMD_UPDATE_SHOW_FORCE_UPDATE = "CMD_UPDATE_SHOW_FORCE_UPDATE";
    public const string CMD_UPDATE_SHOW_HOTFIX = "CMD_UPDATE_SHOW_HOTFIX";
    public const string CMD_UPDATE_RETRY = "CMD_UPDATE_RETRY";
    public const string CMD_UPDATE_LOAD_HOTFIX_CONFIG = "CMD_UPDATE_LOAD_HOTFIX_CONFIG";
    public const string CMD_UPDATE_ENTER_GAME = "CMD_UPDATE_ENTER_GAME";
    public const string CMD_UPDATE_DO_UPDATE_BTN = "CMD_UPDATE_DO_UPDATE_BTN";
    
    public const string COMMON_BACK = "COMMON_BACK";

    /// <summary>
    /// Module层消息通知
    /// </summary>
    /// 

    #region

    //新手引导
    public const string MOUDLE_GUIDE_END_LOCAL = "MOUDLE_GUIDE_END_GUIDE";

    public const string MOUDLE_GUIDE_END_SERVER = "MOUDLE_GUIDE_END_SERVER";

    /// <summary>
    /// 设置服务器引导步骤
    /// 参数1：GuideTypePB
    /// 参数2：引导id，策划配的
    /// </summary>
    public const string MOUDLE_GUIDE_STEP_REMOTE = "MOUDLE_GUIDE_STEP_REMOTE";

    /// <summary>
    /// 服务器返回引导步骤设成功
    /// </summary>
    public const string MOUDLE_GUIDE_RECEIVE_REMOTE_STEP = "MOUDLE_GUIDE_RECEIVE_REMOTE_STEP";

    public const string MOUDLE_GUIDE_SUPPORTERACT_STARTSUCCESS = "MOUDLE_GUIDE_SUPPORTERACT_STARTSUCCESS";


    //创建用户
    public const string MODULE_CREATE_USER_CONFIRM = "MODULE_CREATE_USER_CONFIRM";
    
    public const string MODULE_CREATE_USER_END = "MODULE_CREATE_USER_END";
    
    public const string MODULE_CREATE_BIRTHDAY = "MODULE_CREATE_BIRTHDAY";

    //gameplay
    public const string MODULE_GAMEPLAY_GOTO_MAIN_LINE = "MODULE_GAMEPLAY_GOTO_CITY";

    public const string MODULE_GAMEPLAY_GOTO_SUPPORTERACTIVITY = "MODULE_GAMEPLAY_GOTO_SUPPORTERACTIVITY";

    public const string MODULE_GAMEPLAY_GOTO_RECOLLECTION = "MODULE_GAMEPLAY_GOTO_RECOLLECTION";
    
    public const string MODULE_GAMEPLAY_GOTO_EXERCISE_ROOM = "MODULE_GAMEPLAY_GOTO_EXERCISE_ROOM";

    public const string MODULE_GAMEPLAY_GOTO_VISIT = "MODULE_GAMEPLAY_GOTO_VISIT";

    public const string MODULE_GAMEPLAY_GOTO_TRAININGROOM = "MODULE_GAMEPLAY_GOTO_TRAININGROOM";
    
    public const string MODULE_MAINLINE_SHOW_STORY_VIEW = "MODULE_MAINLINE_SHOW_STORY_VIEW";

    public const string MODULE_MAINLINE_SHOW_BATTLE_VIEW = "MODULE_MAINLINE_SHOW_BATTLE_VIEW";
    
    public const string MODULE_GAMEPLAY_GOTO_SHOPPING = "MODULE_GAMEPLAY_GOTO_SHOPPING";

    //星缘（卡牌收集）
    public const string MODULE_CARD_COLLECTION_SHOW_CARD_DETAIL_VIEW = "MODULE_CARD_COLLECTION_SHOW_CARD_DETAIL_VIEW";
    public const string MODULE_CARD_TABBAR_SELECT_CHANGE = "MODULE_CARD_TABBAR_SELECT_CHANGE";

    public const string MODULE_CARD_COLLECTION_SHOW_MY_CARD = "MODULE_CARD_COLLECTION_SHOW_MY_CARD";
    public const string MODULE_CARD_COLLECTION_CHANEG_VIEW = "MODULE_CARD_COLLECTION_CHANEG_VIEW";

    public const string MODULE_CARD_COLLECTION_BACK_TO_CARD_LIST_VIEW = "MODULE_CARD_COLLECTION_BACK_TO_CARD_LIST_VIEW";

    public const string MODULE_CARD_SHOW_FULLSCREEN_CARD = "MODULE_CARD_SHOW_FULLSCREEN_CARD";
    public const string MODULE_CARD_CLOSE_FULLSCREEN = "MODULE_CARD_CLOSE_FULLSCREEN";

    public const string MODULE_CARD_SHOW_SELECTED_CARD = "MODULE_CARD_SHOW_SELECTED_CARD";  //新手引导，引导卡发送的Message

    //好感度
    /// <summary>
    /// 显示保存和分享VIEW
    /// </summary>
    public const string MODULE_FACORABLILITY_SHOW_SAVEANDSHARE_VIEW = "MODULE_FACORABLILITY_SHOW_SAVEANDSHARE_VIEW";

    /// <summary>
    /// 关闭保存和分享VIEW
    /// </summary>
    public const string MODULE_FACORABLILITY_Close_SAVEANDSHARE_VIEW = "MODULE_FACORABLILITY_Close_SAVEANDSHARE_VIEW";

    public const string MODULE_DISIPOSITION_SHOW_CLOTHPANEL = "MODULE_DISIPOSITION_SHOW_CLOTHPANEL";
    public const string MODULE_DISIPOSITION_SHOW_SHOWPHONEEVENT = "MODULE_DISIPOSITION_SHOW_SHOWPHONEEVENT";
    public const string MODULE_DISIPOSITION_BACKMAINVIEW = "MODULE_DISIPOSITION_BACKMAINVIEW";
    public const string MODULE_FACORABLILITY_ON_SHOW_NPC_INFO = "MODULE_FACORABLILITY_ON_SHOW_NPC_INFO";
    /// <summary>
    /// 服装和背景Toggler
    /// </summary>
    public const string MODULE_FACORABLILITY_TABBAR_SELECT_CHANGE = "MODULE_FACORABLILITY_TABBAR_SELECT_CHANGE";

    // public const string MODULE_FAVORABILITY_ENTER_RELOADINGVIEW = "CMD_FAVORABILITY_ENTER_RELOADINGVIEW"; //进入换装界面

    #endregion


    //好高度主界面
    public const string MODULE_DISIPOSITION_SHOW_CLOTHPANEL_BTN = "MODULE_DISIPOSITION_SHOW_CLOTHPANEL_BTN"; //换装按钮
    public const string MODULE_DISIPOSITION_SHOW_GIVEGIFTS = "MODULE_DISIPOSITION_SHOW_GIVEGIFTS";
    public const string MODULE_DISIPOSITION_SHOW_MAINVIEW = "MODULE_DISIPOSITION_SHOW_MAINVIEW"; //展示到主界面
    public const string MODULE_DISIPOSITION_SHOW_VOICE_WINDOW = "MODULE_DISIPOSITION_SHOW_VOICE_WINDOW";//显示语音收藏窗口s

    //抽卡
    public const string MODULE_CARD_SHOW_DRAW_VIEW = "MODULE_CARD_SHOW_DRAW_VIEW";
    public const string MODULE_DRAWCARD_SHOW_RESULT_PANEL = "MODULE_DRAWCARD_SHOW_RESULT_PANEL";
    public const string MODULE_DRAWCARD_GOBACK = "MODULE_DRAWCARD_GOBACK";
    public const string MODULE_DRAWCARD_SHOW_SHARE_CLICK = "MODULE_DRAWCARD_SHOW_SHARE_CLICK";

    //恋爱日记
    public const string MODULE_LOVEDIARY_SHOW_TEMPLATE_PANEL = "MODULE_LOVEDIARY_SHOW_TEMPLATE_PANEL";
    public const string MODULE_LOVEDIARY_SHOW_EDIT_PANEL = "MODULE_LOVEDIARY_SHOW_EDIT_PANEL";
    public const string MODULE_LOVEDIARY_SHOW_CALENDAR_PANEL = "MODULE_LOVEDIARY_SHOW_CALENDAR_PANEL";

    public const string MODULE_LOVEDIARY_SHOW_CALENDARORTEMPLATE_PANEL =
        "MODULE_LOVEDIARY_SHOW_CALENDARORTEMPLATE_PANEL";

    //探班
    public const string MODULE_VISIT_SHOW_VISIT_PANEL = "MODULE_VISIT_SHOW_VISIT_PANEL";
    public const string MODULE_VISIT_SHOW_WEATHER_PANEL = "MODULE_VISIT_SHOW_WEATHER_PANEL";
    public const string MODULE_VISIT_SHOW_LEVEL_PANEL = "MODULE_VISIT_SHOW_LEVEL_PANEL";
    public const string MODULE_VISIT_WEATHER_SET_BACKBTNSHOWORHIDE = "MODULE_VISIT_WEATHER_SET_BACKBTNSHOWORHIDE";

    //应援会
    public const string MODULE_SUPPOTER_BACK_SUPPOTER = "MODULE_SUPPOTER_BACK_SUPPOTER";
    public const string MODULE_SUPPOTER_CLOSE_SUPPOTER = "MODULE_SUPPOTER_CLOSE_SUPPOTER";
    public const string MODULE_SUPPOTER_GOTO_FRIENDS = "MODULE_SUPPOTER_GOTO_FRIENDS";
    public const string MODULE_SUPPOTER_GOTO_AIRBORNEGAME = "MODULE_SUPPOTER_GOTO_AIRBORNEGAME";
    public const string MODULE_SUPPOTER_GOTO_TAKEPHOTO = "MODULE_SUPPOTER_GOTO_TAKEPHOTO";
    public const string MODULE_SUPPOTER_GOTO_MORN_FANS = "MODULE_SUPPOTER_GOTO_MORN_FANS";

    //剧情
    public const string MODULE_STORY_SHOW_RECORD_VIEW = "MODULE_STORY_SHOW_RECORD_VIEW";


    /// <summary>
    /// Control层消息通知
    /// </summary>
    /// 

    #region

    //登录
    public const string CMD_LOGIN_DO_LOGIN = "MODULE_LOGIN_DO_LOGIN";
    public const string CMD_LOGIN_SWITCH_LOGIN = "CMD_LOGIN_SWITCH_LOGIN";
    public const string CMD_LOGIN_OPEN_REGISTER = "MODULE_LOGIN_OPEN_REGISTER";
    public const string CMD_LOGIN_OPEN_LOGIN = "MODULE_LOGIN_OPEN_LOGIN";
    public const string CMD_LOGIN_ANNOUNCEMENT = "CMD_LOGIN_ANNOUNCEMENT";  //公告按钮
    public const string CMD_LOGIN_LOAD_DATA = "CMD_LOGIN_LOAD_DATA"; //加载公有数据
    public const string CMD_LOGIN_LOAD_DATAFINISHED = "CMD_LOGIN_LOAD_DATAFINISHED"; //完成加载公有数据
    public const string CMD_LOGIN_RESTORE_LOADING_UI = "CMD_LOGIN_RESTORE_LOADING_UI"; //恢复加载界面

    //主场景
    public const string CMD_MAIN_CHANGE_DISPLAY = "MODULE_MAIN_CHANGE_DISPLAY"; //切换主场景菜单显示

   
    public const string CMD_MAIN_ON_START_BTN = "MODULE_MAIN_ON_START_BTN";
    public const string CMD_MAIN_ON_SUPPORTER_BTN = "MODULE_MAIN_ON_SUPPORTER_BTN";
    public const string CMD_MAIN_ON_PHONE_BTN = "MODULE_MAIN_ON_PHONE_BTN";
    public const string CMD_MAIN_ON_ALBUM_BTN = "MODULE_MAIN_ON_ALBUM_BTN";
    public const string CMD_MAIN_ON_MAIL_BTN = "MODULE_MAIN_ON_MAIL_BTN";
    public const string CMD_MAIN_ON_CARD_BTN = "MODULE_MAIN_ON_CARD_BTN";
    public const string CMD_MAIN_ON_DRAWCARD_BTN = "CMD_MAIN_ON_DRAWCARD_BTN";
    public const string CMD_MAIN_ON_STAGINGPOST_BTN = "MODULE_MAIN_ON_STAGINGPOST_BTN";
    public const string CMD_MAIN_ON_GIFT_BTN = "MODULE_MAIN_ON_GIFT_BTN";
    public const string CMD_MAIN_ON_ACTIVITY_BTN = "MODULE_MAIN_ON_ACTIVITY_BTN";
    public const string CMD_MAIN_ON_FULLVIEW_BTN = "MODULE_MAIN_ON_FULLVIEW_BTN";
    public const string CMD_MAIN_ON_CHANGE_ROLE_BTN = "MODULE_MAIN_ON_CHANGE_ROLE_BTN";
    public const string CMD_MAIN_ON_LIVE2DCLICK = "CMD_MAIN_ON_LIVE2DCLICK";

    public const string CMD_MAIN_ON_FIRITSRECHARGE_BTN = "CMD_MAIN_ON_FIRITSRECHARGE_BTN";  //点击首冲Btn
    public const string CMD_MAIN_ON_TOTALRECHARGE_BTN = "CMD_MAIN_ON_TOTALRECHARGE_BTN";//点击累充
    public const string CMD_MAIN_STORESCORECOMMENT = "CMD_MAIN_STORESCORECOMMENT"; //评论完请求

    public const string CMD_MAIN_SHOW_USER_INFO = "MODULE_MAIN_SHOW_USER_INFO";

    public const string CMD_MAIN_SHOW_BUY_GOLD = "CMD_MAIN_SHOW_BUY_GOLD"; //买金币
    public const string CMD_MAIN_SHOW_BUY_POWER = "CMD_MAIN_SHOW_BUY_GEM"; //买体力
    public const string CMD_MAIN_SHOW_BUY_GEM = "CMD_MAIN_SHOW_BUY_Gem";//买星钻

    public const string CMD_MAIN_ON_STAR_ACTIVITY_BTN = "CMD_MAIN_ON_STAR_ACTIVITY_BTN";
    public const string CMD_MAIN_FIRESHDOWNLOADAWARD = "CMD_MAIN_FIRESHDOWNLOADAWARD";

    public const string CMD_MAIN_ON_PLAYERBIRTHDAY = "CMD_MAIN_ON_PLAYERBIRTHDAY"; //迟郁的生日
    public const string CMD_MAIN_ON_ACTIVITYTEMPLATE_BTN = "CMD_MAIN_ON_ACTIVITYTEMPLATE_BTN";//活动模板Btn
    public const string CMD_MAIN_ON_ACTIVITYCAPSULETEMPLATE_BTN = "CMD_MAIN_ON_ACTIVITYCAPSULETEMPLATE_BTN";//活动摇奖模板Btn
    public const string CMD_MAIN_ON_ACTIVITYMUSICTEMPLATE_BTN = "CMD_MAIN_ON_ACTIVITYMUSICTEMPLATE_BTN";    //音游活动模板

    #region 好感度

    public const string CMD_SAVEANDSHARE_VIEW_SAVE = "CMD_SAVEANDSHARE_VIEW_SAVE"; //保存和分享View_SaveBtn
    public const string CMD_SAVEANDSHARE_VIEW_SHARE = "CMD_SAVEANDSHARE_VIEW_SHARE"; //保存和分享View_ShareBtn
    public const string CMD_FAVORABILITY_CLOTHING_TOGGLE = "CMD_FAVORABILITY_CLOTHING_TOGGLE"; //服装Toggle

    public const string CMD_FAVORABILITY_BACKGROUDN_TOGGLE = "CMD_FAVORABILITY_BACKGROUDN_TOGGLE"; //背景Toggle

    //  public const string CMD_FAVORABILITY_GIVEGIFTS_ITEM_ONCLICK = "CMD_FAVORABILITY_GIVEGIFTS_ITEM_ONCLICK"; //赠送礼物道具点击
    public const string CMD_FAVORABILITY_GIVEGIFTS_BTN = "CMD_FAVORABILITY_GIVEGIFTS_BTN"; //赠送礼物按钮
    public const string CMD_FAVORABILITY_SHOW_MAIN = "CMD_FAVORABILITY_SHOW_MAIN"; //显示好感度主界面

    #endregion

    #endregion


    //剧情
    public const string CMD_STORY_RECODE_DIALOG = "CMD_STORY_RECODE_DIALOG";
    public const string CMD_STORY_READY = "CMD_STORY_READY";
    public const string CMD_STORY_END = "CMD_STORY_END";
    public const string CMD_STORY_BRANCH_SELECTED = "CMD_STORY_BRANCH_SELECTED";
    public const string CMD_STORY_ON_EVENT = "CMD_STORY_ON_EVENT";

    //战斗
    public const string CMD_BATTLE_NEXT = "CMD_BATTLE_NEXT";
    public const string CMD_BATTLE_REMOVE_HERO_CARD = "CMD_BATTLE_REMOVE_HERO_CARD";
    public const string CMD_BATTLE_RESULT_DATA = "CMD_BATTLE_RESULT_DATA";
    public const string CMD_BATTLE_CHANGE_POWER = "CMD_BATTLE_CHANGE_POWER";
    public const string CMD_BATTLE_SET_POWER = "CMD_BATTLE_SET_POWER";
    public const string CMD_BATTLE_ITEM_DATA = "CMD_BATTLE_ITEM_DATA";

    public const string CMD_BATTLE_SHOW_SUPPORTER_POWER = "CMD_BATTLE_SHOW_SUPPORTER_POWER";
    public const string CMD_BATTLE_SHOW_SUPPORTER_VIEW = "CMD_BATTLE_SHOW_SUPPORTER_VIEW";

    

    public const string CMD_BATTLE_FANS_CALL_ANIMATION_FINISH = "CMD_BATTLE_FANS_CALL_ANIMATION_FINISH";

   

    public const string CMD_BATTLE_SECOND_SHOW_FANS = "CMD_BATTLE_SECOND_SHOW_FANS";
    public const string CMD_BATTLE_SEND_ROLE_ID = "CMD_BATTLE_SEND_ROLE_ID";

    public const string CMD_BATTLE_GET_RES = "CMD_BATTLE_GET_RES";

   

    public const string CMD_BATTLE_HIDE_PROGRESS = "CMD_BATTLE_HIDE_PROGRESS"; //开始放过场动画时要隐藏进度

   
    
    //探班战斗
    public const string CMD_VISITBATTLE_NEXT = "CMD_VISITBATTLE_NEXT";
    public const string CMD_VISITBATTLE_REMOVE_HERO_CARD = "CMD_VISITBATTLE_REMOVE_HERO_CARD";
    public const string CMD_VISITBATTLE_RESULT_DATA = "CMD_VISITBATTLE_RESULT_DATA";
    public const string CMD_VISITBATTLE_CHANGE_POWER = "CMD_VISITBATTLE_CHANGE_POWER";
    public const string CMD_VISITBATTLE_SET_POWER = "CMD_VISITBATTLE_SET_POWER";
    public const string CMD_VISITBATTLE_ITEM_DATA = "CMD_VISITBATTLE_ITEM_DATA";

    public const string CMD_VISITBATTLE_SHOW_SUPPORTER_POWER = "CMD_VISITBATTLE_SHOW_SUPPORTER_POWER";
    public const string CMD_VISITBATTLE_SHOW_SUPPORTER_VIEW = "CMD_VISITBATTLE_SHOW_SUPPORTER_VIEW";

    public const string CMD_VISITBATTLE_SHOW_SUPPORTER_ANIMATION = "CMD_VISITBATTLE_SHOW_SUPPORTER_ANIMATION";
    public const string CMD_VISITBATTLE_MOVE_TO_END = "CMD_VISITBATTLE_SHOW_SUPER_STAR_PANEL";

    public const string CMD_VISITBATTLE_FANS_CALL_ANIMATION_FINISH = "CMD_VISITBATTLE_FANS_CALL_ANIMATION_FINISH";


    //星缘(卡牌收集)
    public const string CMD_CARD_COLLECTION_GET_USER_PUZZLUE = "MODULE_SHOW_CARD_FRAGMENT";
    public const string CMD_CARD_RESOLVE = "CMD_CARD_RESOLVE";
    public const string CMD_CARD_UPGRADE_STAR = "CMD_CARD_UPGRADE_STAR";
    public const string CMD_CARD_UPGRADE_LEVEL = "CMD_CARD_UPGRADE_LEVEL";
    public const string CMD_CARD_UPGRADE_ONELEVEL = "CMD_CARD_UPGRADE_ONELEVEL";

    public const string CMD_CARD_EVOLUTION = "CMD_CARD_EVOLUTION";
    public const string CMD_CARD_LOVE = "CMD_CARD_LOVE";

    //public const string CMD_CARD_CONFIRMEVOLUTION = "CMD_CARD_CONFIRMEVOLUTION";
    public const string CMD_CARD_REFRESH_USER_CARDS = "CMD_CARD_REFRESH_USER_CARDS";
    public const string CMD_CARD_CHOOSE_EVO = "CMD_CARD_CHOOSE_EVO";

    public const string CMD_CARD_GET_MORE_PROPS = "CMD_CARD_GET_MORE_PROPS";
    public const string CMD_CARD_SHOPSTARUPPREVIEW = "CMD_CARD_SHOPSTARUPPREVIEW";

    //抽卡
    public const string CMD_DRAWCARD_GET_CARDLIST = "CMD_DRAWCARD_GET_CARDLIST";

    public const string MODULE_VIEW_BACK_DRAWCARD = "MODULE_VIEW_BACK_DRAWCARD";
    public const string MODULE_DRAWCARD_GOTO_CARD_COLLECTION = "MODULE_DRAWCARD_GOTO_CARDCOLLECTION";

    public const string CMD_DRAWCARD_GET_CARD = "CMD_DRAWCARD_GET_CARD";

    public const string CMD_DRAWCARD_GEM_DRAW_TEN = "CMD_DRAWCARD_GEM_DRAW_TEN";
    public const string CMD_DRAWCARD_GEM_DRAW_ONCE = "CMD_DRAWCARD_GEM_DRAW_ONCE";
    public const string CMD_DRAWCARD_GOLD_DRAW_ONCE = "CMD_DRAWCARD_GOLD_DRAW_ONCE";
    public const string CMD_DRAWCARD_GOLD_DRAW_TEN = "CMD_DRAWCARD_GOLD_DRAW_TEN";
    public const string CMD_DRAWCARD_GOTO_GOLD_DRAW = "CMD_DRAWCARD_GOTO_GOLD_DRAW";
    public const string CMD_DRAWCARD_DRAWCARD = "CMD_DRAWCARD_DRAWCARD";

    public const string CMD_DRAWCARD_LIMIT_DRAW_ONCE = "CMD_DRAWCARD_LIMIT_DRAW_ONCE";
    public const string CMD_DRAWCARD_LIMIT_DRAW_TEN = "CMD_DRAWCARD_LIMIT_DRAW_TEN";

    public const string CMD_DRAWCARD_ACTIVITY_DRAW_ONCE = "CMD_DRAWCARD_ACTIVITY_DRAW_ONCE";
    public const string CMD_DRAWCARD_ACTIVITY_DRAW_TEN = "CMD_DRAWCARD_ACTIVITY_DRAW_TEN";


    //应援会
    public const string CMD_SUPPOTER_CHANGENAME = "CMD_SUPPOTER_CHANGENAME";
    public const string CMD_SUPPOTER_UPGRADE = "CMD_SUPPOTER_UPGRADE";
    public const string CMD_SUPPOTER_RECEIVEGIFT = "CMD_SUPPOTER_RECEIVEGIFT";


    //好友
    public const string MODULE_FRIENDS_GOTO_MAKE_FRIENDS = "MODULE_FRIENDS_GOTO_MAKE_FRIENDS";
    public const string MODULE_FRIENDS_GOBACK = "MODULE_FRIENDS_GOBACK";
    public const string CMD_FRIENDS_GRTPOWER = "CMD_FRIENDS_GRTPOWER";
    public const string CMD_FRIENDS_GIVEAllPOWER = "CMD_FRIENDS_GIVEPOWER";
    public const string CMD_FRIENDS_DELETE_FRIEND = "CMD_FRIENDS_DELETE_FRIEND";
    public const string CMD_FRIENDS_DOAPPLY = "CMD_FRIENDS_DOAPPLY";
    public const string CMD_FRIENDS_AGREE = "CMD_FRIENDS_AGREE";
    public const string CMD_FRIENDS_SEARCH = "CMD_FRIENDS_SEARCH";
    public const string CMD_FRIENDS_REFRESH = "CMD_FRIENDS_REFRESH";


    //战斗
    public const string CMD_BATTLE_RESTART = "CMD_BATTLE_RESTART";
    public const string CMD_BATTLE_SHOW_REWARD = "CMD_BATTLE_SHOW_REWARD";
    public const string CMD_BATTLE_SHOW_FAIL = "CMD_BATTLE_SHOW_FAIL";
    public const string CMD_BATTLE_SHOW_BATTLE_WIN_ANIMATION = "CMD_BATTLE_SHOW_COMMENT";
    public const string CMD_BATTLE_SUPERSTAR_CONFIRM = "CMD_BATTLE_SUPERSTAR_CONFIRM";
    public const string CMD_BATTLE_SUPERSTAR_CONFIRM_ERROR1 = "CMD_BATTLE_SUPERSTAR_CONFIRM_ERROR1";
    public const string CMD_BATTLE_FINISH = "CMD_BATTLE_FINISH";

 

    //探班战斗
    public const string CMD_VISITBATTLE_RESTART = "CMD_VISITBATTLE_RESTART";
    public const string CMD_VISITBATTLE_SHOW_REWARD = "CMD_VISITBATTLE_SHOW_REWARD";
    public const string CMD_VISITBATTLE_SHOW_FAIL = "CMD_VISITBATTLE_SHOW_FAIL";
    public const string CMD_VISITBATTLE_SHOW_BATTLE_WIN_ANIMATION = "CMD_VISITBATTLE_SHOW_COMMENT";
    public const string CMD_VISITBATTLE_SUPERSTAR_CONFIRM = "CMD_VISITBATTLE_SUPERSTAR_CONFIRM";
    public const string CMD_VISITBATTLE_SUPERSTAR_CONFIRM_ERROR1 = "CMD_VISITBATTLE_SUPERSTAR_CONFIRM_ERROR1";
    public const string CMD_VISITBATTLE_FINISH = "CMD_VISITBATTLE_FINISH";
    public const string CMD_VISITBATTLE_SUPERSTAR_QUICKSELECT = "CMD_VISITBATTLE_SUPERSTAR_QUICKSELECT";

    public const string CMD_VISITBATTLE_SET_FINISH_DATA = "CMD_VISITBATTLE_SET_FINISH_DATA";

    //手机
    public const string CMD_PHONE_SHOW_SMS = "CMD_PHONE_SHOW_SMS";
    public const string CMD_PHONE_SHOW_TELE = "CMD_PHONE_SHOW_TELE";
    public const string CMD_PHONE_SHOW_FRIENDS = "CMD_PHONE_SHOW_FRIENDS";
    public const string CMD_PHONE_SHOW_WEIBO = "CMD_PHONE_SHOW_WEIBO";
    public const string CMD_PHONE_RULE_DATA = "CMD_PHONE_RULE_DATA";
    public const string CMD_PHONE_MY_DATA = "CMD_PHONE_MY_DATA";
    public const string CMD_PHONE_MY_DATA_READY = "CMD_PHONE_MY_DATA_READY";
    public const string CMD_PHONE_GUIDE_BACKBTN = "CMD_PHONE_GUIDE_BACKBTN"; 

    public const string CMD_PHONE_GUIDE_GOTO_SMSITEM = "CMD_PHONE_GUIDE_GOTO_SMSITEM";
    public const string CMD_PHONE_GUIDE_OPEN_INPUTBAR = "CMD_PHONE_GUIDE_OPEN_INPUTBAR";
    public const string CMD_PHONE_GUIDE_OPEN_SELECTITEM = "CMD_PHONE_GUIDE_OPEN_SELECTITEM";

    public const string CMD_PHONE_READ_SMS = "CMD_PHONE_READ_SMS";
    //public const string CMD_PHONE_UPDATE_SMS_DATA = "CMD_PHONE_UPDATE_SMS_DATA";
    //public const string CMD_PHONE_UPDATE_CALL_DATA = "CMD_PHONE_UPDATE_CALL_DATA";

    public const string CMD_PHONE_SMS_CUR = "CMD_PHONE_SMS_CUR";
    public const string CMD_PHONE_SMS_HISTORY = "CMD_PHONE_SMS_HISTORY";
    public const string CMD_PHONE_SMS_DETAIL = "CMD_PHONE_SMS_DETAIL";

    public const string CMD_PHONE_SMS_CHOOSE = "CMD_PHONE_SMS_CHOOSE";
    public const string CMD_PHONE_SMS_LISTEN = "CMD_PHONE_SMS_LISTEN";
    public const string CMD_PHONE_SMS_SHOWDETAIL = "CMD_PHONE_SMS_SHOWDETAIL";
    public const string CMD_PHONE_CALL_SHOWDETAIL = "CMD_PHONE_CALL_SHOWDETAIL";
    public const string CMD_PHONE_TELE_CHOOSE = "CMD_PHONE_TELE_CHOOSE";

    public const string CMD_PHONE_FRIENDCIRCLE_DATA = "CMD_PHONE_FRIENDCIRCLE_DATA";

    //public const string CMD_PHONE_UPDATE_FRIENDCIRCLE_DATA = "CMD_PHONE_UPDATE_FRIENDCIRCLE_DATA";
    public const string CMD_PHONE_WEIBO_DATA = "CMD_PHONE_WEIBO_DATA";
    //public const string CMD_PHONE_UPDATE_WEIBO_DATA = "CMD_PHONE_UPDATE_WEIBO_DATA";

    public const string CMD_PHONE_CALL_HANGUP = "CMD_PHONE_CALL_HANGUP";
    public const string CMD_PHONE_CALL_ANSWER = "CMD_PHONE_CALL_ANSWER";

    public const string CMD_PHONE_ALL_DATA = "CMD_PHONE_ALL_DATA";
    public const string CMD_PHONE_UPDATE_BG_REDPOINT = "CMD_PHONE_UPDATE_BG_REDPOINT";
    public const string CMD_PHONE_HIDE_BG_REDPOINT = "CMD_PHONE_HIDE_BG_REDPOINT";

    //任务
    public const string CMD_TASK_SHOW_DAILYTASK = "CMD_TASK_SHOW_DAILYTASK";
    public const string CMD_TASK_SHOW_SUPPORTERTASK = "CMD_TASK_SHOW_SUPPORTERTASK";
    public const string CMD_TASK_RECEIVE_ACTREWARD = "CMD_TASK_RECEIVE_ACTREWARD";
    public const string CMD_RECOREDSTATE = "CMD_RECOREDSTATE";

    //哄睡
    public const string MODULE_SLEEP_CHOOSE_VIEW_BTN_ROLE = "MODULE_SLEEP_CHOOSE_VIEW_BTN_ROLE";

    //恋爱约会
    public const string CMD_APPOINTMENT_SHOW_CHOOSEROLE = "CMD_APPOINTMENT_SHOW_CHOOSEROLE";
    public const string CMD_APPOINTMENT_JUMPCHOOSEROLE = "CMD_APPOINTMENT_JUMPCHOOSEROLE";
    public const string CMD_APPOINTMENT_SHOW_JOURNALCHOOSE = "CMD_APPOINTMENT_SHOW_JOURNALCHOOSE";
    public const string CMD_APPOINTMENT_SHOW_LOVESTORY = "CMD_APPOINTMENT_SHOW_LOVESTORY";
    public const string CMD_APPOINTMENT_ACTIVE_LOVESTORY = "CMD_APPOINTMENT_ACTIVE_LOVESTORY";
    public const string CMD_APPOINTMENT_SHOW_NOCARD = "CMD_APPOINTMENT_SHOW_NOCARD";
    public const string CMD_APPOINTMENT_JUMPTODAILY = "CMD_APPOINTMENT_JUMPTODAILY";

    public const string CMD_APPOINTMENT_ACTIVE_PHOTOCLEARUP = "CMD_APPOINTMENT_ACTIVE_PHOTOCLEARUP";

    //public const string CMD_APPOINTMENT_OPEN_GATE = "CMD_APPOINTMENT_OPEN_GATE";
    public const string CMD_APPOINTMENT_ENSUREOPENGATE = "CMD_APPOINTMENT_ENSUREOPENGATE";
    public const string CMD_APPOINTMENT_UPDATE_LOVESTORY = "CMD_APPOINTMENT_UPDATE_LOVESTORY";
    public const string CMD_lOVEAPPOINTMENT_STORYEND = "CMD_lOVEAPPOINTMENT_STORYEND";

    //恋爱日记
    public const string CMD_LOVEDIARY_PREVIOUS_MONTH = "CMD_LOVEDIARY_PREVIOUS_MONTH";
    public const string CMD_LOVEDIARY_NEXT_MONTH = "CMD_LOVEDIARY_NEXT_MONTH";
    public const string CMD_LOVEDIARY_CALENDAR_SELECT = "CMD_LOVEDIARY_CALENDAR_SELECT";
    public const string CMD_LOVEDIARY_TEMPLATE_SELECT = "CMD_LOVEDIARY_TEMPLATE_SELECT";
    public const string CMD_LOVEDIARY_EDIT_SAVE = "CMD_LOVEDIARY_EDIT_SAVE";

    public const string CMD_LOVEDIARY_ENTER_EDITTYPE = "CMD_LOVEDIARY_ENTER_EDITTYPE";

    public const string CMD_LOVEDIARY_ENTER_SELECT_IMAGE = "CMD_LOVEDIARY_ENTER_SELECT_IMAGE";
    public const string CMD_LOVEDIARY_ENTER_SELECT_NONE = "CMD_LOVEDIARY_ENTER_SELECT_NONE";
    public const string CMD_LOVEDIARY_ENTER_SELECT_LABEL = "CMD_LOVEDIARY_ENTER_SELECT_LABEL";
    //探班
    public const string CMD_VISIT_WEATHER_JUMP_CLICK = "CMD_VISIT_WEATHER_JUMP_CLICK";
    public const string CMD_VISIT_WEATHER_BLESSING_CLICK = "CMD_VISIT_WEATHER_BLESSING_CLICK";
    public const string CMD_VISIT_WEATHER_RESULT_CLICK = "CMD_VISIT_WEATHER_RESULT_CLICK";
    public const string CMD_VISIT_LEVEL_FIRSTAWARDGET_CLICK = "CMD_VISIT_LEVEL_FIRSTAWARDGET_CLICK";
    public const string CMD_VISIT_LEVEL_SAVEITEMPOS = "CMD_VISIT_LEVEL_SAVEITEMPOS";

    //应援活动
    public const string CMD_SUPPORTERACTIVITY_SHOW_FANSDETAIL = "CMD_SUPPORTERACTIVITY_SHOW_FANSDETAIL";
    public const string CMD_SUPPORTERACTIVITY_STARTACTIVITY = "CMD_SUPPORTERACTIVITY_STARTACTIVITY";
    public const string CMD_SUPPORTERACTIVITY_STARTSUCCESS = "CMD_SUPPORTERACTIVITY_STARTSUCCESS";
    public const string CMD_SUPPORTERACTIVITY_GETREWARD = "CMD_SUPPORTERACTIVITY_GETREWARD";
    public const string CMD_SUPPORTERACTIVITY_DONEIMMEDIATE = "CMD_SUPPORTERACTIVITY_DONEIMMEDIATE";
    public const string CMD_SUPPORTERACTIVITY_REFRESH = "CMD_SUPPORTERACTIVITY_REFRESH";
    public const string CMD_SUPPORTERACTIVITY_GOBACK = "CMD_SUPPORTERACTIVITY_GOBACK";
    public const string CMD_SUPPORTERACTIVITY_REWARDTIPS = "CMD_SUPPORTERACTIVITY_REWARDTIPS";
    public const string CMD_SUPPORTERACTIVITY_GETMYENCOURAGE = "CMD_SUPPORTERACTIVITY_GETMYENCOURAGE";
    public const string CMD_SUPPORTERACTIVITY_OPENPROPORG = "CMD_SUPPORTERACTIVITY_OPENPROPORG";
    public const string CMD_SUPPORTERACTIVITY_BUYENCOURAGEPOWER = "CMD_SUPPORTERACTIVITY_BUYENCOURAGEPOWER"; //购买星源体力
    public const string CMD_SUPPORTERACTIVITY_GUIDETOFANSMODULE = "CMD_SUPPORTERACTIVITY_GUIDETOFANSMODULE";//功能引导
    public const string CMD_SUPPORTERACTIVITY_GUIDETODOINGACT = "CMD_SUPPORTERACTIVITY_GUIDETODOINGACT";//引导回活动界面
    public const string CMD_SUPPORTERACTIVITY_BuyInner = "CMD_SUPPORTERACTIVITY_BuyInner";     //购买次数
    public const string MODULE_SUPPORTERACTIVITY_GOBACKANDCHANGE = "MODULE_SUPPORTERACTIVITY_GOBACKANDCHANGE";  //后退更换应援活动
    public const string MODULE_SUPPORTERACTIVITY_JUMPTOOTHER = "MODULE_SUPPORTERACTIVITY_JUMPTOOTHER";//跳转到星盘
    
    //星缘回忆
    public const string MODULE_RECOLLECTION_SHOW_CHOOSE_CARD = "MODULE_RECOLLECTION_SHOW_CHOOSE_CARD";
    public const string MODULE_RECOLLECTION_CARD_SELECTED = "MODULE_RECOLLECTION_CARD_SELECTED";
    public const string MODULE_RECOLLECTION_PLAY = "MODULE_RECOLLECTION_PLAY";
    public const string MODULE_RECOLLECTION_SHOW_CARD_DROP_PROP = "MODULE_RECOLLECTION_SHOW_CARD_DROP_PROP";
    public const string CMD_RECOLLECTION_BUY_ENERGY = "CMD_RECOLLECTION_BUY_ENERGY";
    public const string CMD_RECOLLECTION_BUY_COUNT = "CMD_RECOLLECTION_BUY_COUNT";
    public const string CMD_RECOLLECTION_SHOW_REWARD = "CMD_RECOLLECTION_SHOW_REWARD";
    public const string CMD_RECOLLECTION_SENDBUYEVENT = "CMD_RECOLLECTION_SENDBUYEVENT";

    public const string CMD_RECOLLECTION_SHOW_BUY_DESC = "CMD_RECOLLECTION_SHOW_BUY_DESC";
    //好感度
    public const string CMD_FACORABLILITY_VIEW_ONSAVE_BTN = "CMD_FACORABLILITY_VIEW_ONSAVE_BTN"; //换装页面SaveBtn
    public const string CMD_FACORABLILITY_JUMPTOCRADS = "CMD_FACORABLILITY_JUMPTOCRADS";
    public const string CMD_FACORABLILITY_PLAT_NPC_INFO_VOICE = "CMD_FACORABLILITY_PLAT_NPC_INFO_VOICE";//播放NpcInfo默认语音

  //  public const string CMD_DISIPOSITION_SHOW_GIVEGIFTS = "CMD_DISIPOSITION_SHOW_GIVEGIFTS"; //赠送礼物
    public const string CMD_DISIPOSITION_REMO_GIVEGIFTS_ITEM = "CMD_DISIPOSITION_REMO_GIVEGIFTS_ITEM"; //移除道具数量为0的道具
  
    public const string CMD_FACORABLILITY_COMETOMAIN = "CMD_FACORABLILITY_COMETOMAIN"; //进入主界面
    public const string CMD_FACORABLILITY_BACKTOFAVORABILITY = "CMD_FACORABLILITY_BACKTOFAVORABILITY";
    public const string CMD_FACORABLILITY_DESTROY_PANEL = "CMD_FACORABLILITY_DESTROY_PANEL"; //删除当前panel
    public const string CMD_FACORABLILITY_ENTER_SEND_GIVE_GIFTS = "CMD_FACORABLILITY_ENTER_SEND_GIVE_GIFTS"; //进入送礼
    public const string CMD_FACORABLILITY_TIGGER_LIVE2D_VOICE = "CMD_FACORABLILITY_TIGGER_LIVE2D_VOICE";  //送礼结束触发语音
    public const string CMD_FACORABLILITY_GOBACK = "CMD_FACORABLILITY_GOBACK";//退出好感度模块
    //换装
    public const string CMD_RELOADING_RESET_CLOTH_RED_FRAME = "CMD_RELOADING_RESET_CLOTH_RED_FRAME";//重置服装红框状态
    public const string CMD_RELOADING_RESET_BACKGROUND_RED_FARME = "CMD_RELOADING_RESET_BACKGROUND_RED_FARME";//重置背景红框状态
    
    //活动
    public const string CMD_ACTIVITY_SHOW_ACTIVITYDATA = "CMD_ACTIVITY_SHOW_ACTIVITYDATA";  //显示活动数据
    public const string CMD_ACTIVITY_REFRESH_ACTIVITYUSER_DATA = "CMD_ACTIVITY_REFRESH_ACTIVITYUSER_DATA";//刷新玩家数据
    public const string CMD_ACTIVITY_REFRESH_ACTIVITYTOGGLE_REDDOT = "CMD_ACTIVITY_REFRESH_ACTIVITYTOGGLE_REDDOT";//刷新红点
    public const string CMD_ACTIVITY_MONTH_SIGIN_GET_BTN = "CMD_ACTIVITY_MONTH_SIGIN_GET_BTN";   //月签累计签到领取
    public const string CMD_ACTIVITY_FIRST_RECHARGE_BTN = "CMD_ACTIVITY_FIRST_RECHARGE_BTN";       //首冲充值按钮
    public const string CMD_ACTIVITY_FIRSTRECHARGE_GET_BTN = "CMD_ACTIVITY_FIRSTRECHARGE_GET_BTN"; //首冲领取按钮  
   // public const string CMD_ACTIVITY_SEND_SEVEN_ACTIVITY_REQ = "CMD_ACTIVITY_SEND_SEVEN_ACTIVITY_REQ";  //七天签到请求 
   // public const string CMD_ACTIVITY_SEVENDAYS_SELECT_CARD = "CMD_ACTIVITY_SEVENDAYS_SELECT_CARD";    //七天选卡

   // public const string CMD_ACTIVITY_DESTROY_OTHER_PANEL = "CMD_ACTIVITY_DESTROY_OTHER_PANEL";//销毁其他Panel
    public const string CMD_ACTIVITY_HINT_BAR_AND_BACKBTN = "CMD_ACTIVITY_HINT_BAR_AND_BACKBTN";//隐藏返回按钮和BarTog
    public const string CMD_ACTIVITY_SHOW_BAR_AND_BACKBTN = "CMD_ACTIVITY_SHOW_BAR_AND_BACKBTN"; //显示返回按钮和BarTog
    public const string CMD_ACTIVITY_REFRESHACTIVITYDA = "CMD_ACTIVITY_REFRESHACTIVITYDA";  //刷新活动数据
    public const string CMD_ACTIVITY_SIXREFRESHACTIVITY = "CMD_ACTIVITY_SIXREFRESHACTIVITY";//6点刷新活动数据
    public const string CMD_ACTIVITY_ONSHOW = "CMD_ACTIVITY_ONSHOW";
    public const string CMD_ACTIVITY_GO_FLOW = "CMD_ACTIVITY_GO_FLOW"; //前往关注
    public const string CMD_ACTIVITY_GO_JOIN = "CMD_ACTIVITY_GO_JOIN"; //加入群聊
    public const string CMD_ACTIVITY_SEVENDAYGUIDE = "CMD_ACTIVITY_SEVENDAYGUIDE";   //活动七日登录引导
    
    //邮件
    public const string CMD_MAIL_A_KEY_TO_GET = "CMD_MAIL_A_KEY_TO_GET";  //一键获取
    public const string CMD_MAIL_A_KEY_TO_DELETE = "CMD_MAIL_A_KEY_TO_DELETE"; //一键删除
    
    //商店
    public const string CMD_REFRESHGOLDMALLITEM = "CMD_REFRESHGOLDMALLITEM";
    public const string CMD_REGETSHOPRULE = "CMD_REGETSHOPRULE";
    public const string CMD_USETASTECARD = "CMD_BUYTASTECARD";
    public const string CMD_BUYMONTHCARD = "CMD_BUYMONTHCARD";
    public const string CMD_MALL_DAILYGEMREWARD = "CMD_MALL_DAILYGEMREWARD";
    public const string CMD_MALL_ENTERTOBUYGEM = "CMD_MALL_ENTERTOBUYGEM"; 
    public const string CMD_MALL_BACKTOMAIN = "CMD_MALL_BACKTOMAIN";
    public const string CMD_MALL_BUYFREEGIFT = "CMD_MALL_BUYFREEGIFT";
    //拍照小游戏
    public const string CMD_TAKEPHOTOS_SHOW_SCORE = "CMD_TAKEPHOTOS_SHOW_SCORE";

    //成就
    public const string CMD_GOTOACHIEVEMENT = "CMD_GOTOACHIEVEMENT";
    public const string CMD_CHOOSEROLE = "CMD_CHOOSEROLE";
    public const string CMD_ACHIEVEMENTBACK = "CMD_ACHIEVEMENTBACK";
    public const string CMD_GOTORECHARGE = "CMD_GOTORECHARGE";

    //空降小游戏
    public const string MODULE_AIRBORNEGAME_SHOW_COUNTDOWN_PANEL = "MODULE_AIRBORNEGAME_SHOW_COUNTDOWN_PANEL";
    public const string MODULE_AIRBORNEGAME_ClOSE_COUNTDOWN_PANEL = "MODULE_AIRBORNEGAME_ClOSE_COUNTDOWN_PANEL";
    public const string CMD_AIRBORNEGAME_START_GAME = "MODULE_AIRBORNEGAME_START_GAME";
    public const string CMD_AIRBORNEGAME_GET_GAME_AWARD = "CMD_AIRBORNEGAME_GET_GAME_AWARD";
    public const string MODULE_AIRBORNEGAME_OVER_GAME = "MODULE_AIRBORNEGAME_OVER_GAME";
    public const string MODULE_AIRBORNEGAME_SHOW_PAUSE_PANEL = "MODULE_AIRBORNEGAME_SHOW_PAUSE_PANEL";
    public const string MODULE_AIRBORNEGAME_CLOSE_PAUSE_PANEL = "MODULE_AIRBORNEGAME_CLOSE_PAUSE_PANEL";
    public const string MODULE_AIRBORNEGAME_SHOW_AWARD_PANEL = "MODULE_AIRBORNEGAME_SHOW_AWARD_PANEL";

    //音友
    public const string MODULE_MUSICRHYRHM_SHOW_COUNTDOWN_PANEL = "MODULE_MUSICRHYRHM_SHOW_COUNTDOWN_PANEL";
    public const string MODULE_MUSICRHYRHM_RESTARTGAME = "MODULE_MUSICRHYRHM_RESTARTGAME";
    
    public const string MODULE_MUSICRHYRHM_ClOSE_COUNTDOWN_PANEL = "MODULE_MUSICRHYRHM_ClOSE_COUNTDOWN_PANEL";
    public const string MODULE_MUSICRHYRHM_SHOW_RESULT_PANEL = "MODULE_MUSICRHYRHM_SHOW_RESULT_PANEL";
    public const string MODULE_MUSICRHYRHM_PAUSE_GAME = "MODULE_MUSICRHYRHM_PAUSE_GAME";
    public const string MODULE_MUSICRHYRHM_CONTINUE_GAME = "MODULE_MUSICRHYRHM_CONTINUE_GAME";
    //练习室
    public const string MODULE_TRAININGROOM_GOTO_PLAY_PANEL = "MODULE_TRAININGROOM_GOTO_PLAY_PANEL";        
    public const string MODULE_TRAININGROOM_GOTO_RANKING_PANEL = "MODULE_TRAININGROOM_GOTO_RANKING_PANEL";  
    public const string MODULE_TRAININGROOM_GOTO_SHOP_PANEL = "MODULE_TRAININGROOM_GOTO_SHOP_PANEL";
    public const string MODULE_TRAININGROOM_GOTO_CHOOSECARD_PANEL = "MODULE_TRAININGROOM_GOTO_CHOOSECARD_PANEL";
    public const string MODULE_TRAININGROOM_SHOW_BACKBTN = "MODULE_TRAININGROOM_SHOW_BACKBTN";
    public const string MODULE_TRAININGROOM_SHOW_SONGCHOOSEVIEW_BACKBTN = "MODULE_TRAININGROOM_SHOW_SONGCHOOSEVIEW_BACKBTN";
    public const string MODULE_TRAININGROOM_GET_RES_FAILED = "MODULE_TRAININGROOM_GET_RES_FAILED";
    public const string MODULE_TRAININGROOM_CHOOSE_NUM_ENOUGH = "MODULE_TRAININGROOM_CHOOSE_NUM_ENOUGH";
    public const string CMD_TRAININGROOM_ONCLICK_UNFOLD_BTN = "CMD_TRAININGROOM_ONCLICK_UNFOLD_BTN";//点击展开按钮
    
    public const string CMD_TRAININGROOM_EXCHANGESHOP_OPEN_REFRESH_NOTARIZE_WINDOW = "CMD_TRAININGROOM_EXCHANGESHOP_OPEN_REFRESH_NOTARIZE_WINDOW";
    public const string CMD_TRAININGROOM_RANKING_LEFT_OR_RIGHT_MOVE = "CMD_TRAININGROOM_RANKING_LEFT_OR_RIGHT_MOVE";
    public const string CMD_TRAININGROOM_CREATE_CHOOSE_CARD = "CMD_TRAININGROOM_CREATE_CHOOSE_CARD";

    //拍照
    public const string MODULE_TAKEPHOTOSGAME_GOTO_START_PANEL = "MODULE_TAKEPHOTOSGAME_GOTO_START_PANEL";
    public const string MODULE_TAKEPHOTOSGAME_GOTO_COUNTDOWN_PANEL = "MODULE_TAKEPHOTOSGAME_GOTO_COUNTDOWN_PANEL";
    public const string MODULE_TAKEPHOTOSGAME_GOTO_RESULT_PANEL = "MODULE_TAKEPHOTOSGAME_GOTO_RESULT_PANEL";
    public const string CMD_TAKEPHOTOSGAME_START_GAME_ONCLICK = "CMD_TAKEPHOTOSGAME_START_GAME_ONCLICK";
    public const string CMD_TAKEPHOTOSGAME_SCORE_VIEW_ONCLICK = "CMD_TAKEPHOTOSGAME_SCORE_VIEW_ONCLICK";
    public const string CMD_TAKEPHOTOSGAME_BUYTIME_ONCLICK = "CMD_TAKEPHOTOSGAME_BUYTIME_ONCLICK";
    public const string MODULE_TAKEPHOTOSGAME_GOTO_INTRODUCTION_PANEL = "MODULE_TAKEPHOTOSGAME_GOTO_INTRODUCTION_PANEL";
    public const string MODULE_TAKEPHOTOSGAME_HIDE_BACKBTN = "MODULE_TAKEPHOTOSGAME_HIDE_BACKBTN";
    public const string MODULE_TAKEPHOTOSGAME_SHOW_BACKBTN = "MODULE_TAKEPHOTOSGAME_SHOW_BACKBTN";

    //引导层发送给逻辑层
    public const string GUIDE_BATTLE_SUPPORTER_OK = "GUIDE_BATTLE_SUPPORTER_OK";
    public const string GUIDE_LOVE_CHOOSETYPE = "GUIDE_LOVE_CHOOSETYPE";
    public const string GUIDE_LOVEAPPOINTMENT_ENTERLOVECHOOSE = "GUIDE_LOVEAPPOINTMENT_ENTERLOVECHOOSE";
    public const string GUIDE_LOVEAPPOINTMENT_ENTERDAILY = "GUIDE_LOVEAPPOINTMENT_ENTERDAILY";
    public const string GUIDE_LOVE_COAXSLEEP = "GUIDE_LOVE_COAXSLEEP";
    public const string GUIDE_ACHIEVEMENT_JUMPTOACHIEVEMENT = "GUIDE_ACHIEVEMENT_JUMPTOACHIEVEMENT";
    public const string CMD_APPOINTMENT_GUIDE_JOURNALCHOOSE = "CMD_APPOINTMENT_GUIDE_JOURNALCHOOSE";
    public const string CMD_APPOINTMENT_GUIDE_NEXTPAGE = "CMD_APPOINTMENT_GUIDE_NEXTPAGE";
    public const string CMD_LOVE_GUIDE_GOBACKTOMAINVIEW = "CMD_LOVE_GUIDE_GOBACKTOMAINVIEW";
    public const string CMD_APPOINTMENT_GUIDE_BACKTOLOVEMAIN = "CMD_APPOINTMENT_GUIDE_BACKTOLOVEMAIN";
    public const string UIDE_LOVEAPPOINTMENT_ENDSUCCESS = "UIDE_LOVEAPPOINTMENT_ENDSUCCESS";
    
    public const string TO_GUIDE_BATTLE_SUPERSTAR_START = "GUIDE_BATTLE_SUPERSTAR_START";
    
    public const string GUIDE_BATTLE_SUPERSTAR_CONFIRM = "GUIDE_BATTLE_SUPERSTAR_CONFIRM";
    
    public const string TO_GUIDE_MAINLINE_GETDATA = "TO_GUIDE_MAINLINE_GETDATA";
    
    public const string TO_GUIDE_BATTLE_FAIL = "TO_GUIDE_BATTLE_FAIL";
    
    public const string TO_GUIDE_BATTLE_RESULT = "TO_GUIDE_BATTLE_RESULT";
    
    public const string TO_GUIDE_CARD_LEVELUP = "TO_GUIDE_CARD_LEVELUP";

    public const string TO_GUIDE_DRAWCARD_RESULT = "TO_GUIDE_DRAWCARD_RESULT";
    public const string TO_GUIDE_DRAWCARD_GOLD = "TO_GUIDE_DRAWCARD_GOLD";
    public const string TO_GUIDE_DRAWCARD_GEM = "TO_GUIDE_DRAWCARD_GEM";
    public const string TO_GUIDE_DRAWCARD_SHOWGUIDE = "TO_GUIDE_DRAWCARD_SHOWGUIDE";
    public const string TO_GUIDE_DRAWCARD_HIDEGUIDE = "TO_GUIDE_DRAWCARD_HIDEGUIDE";
    public const string TO_GUIDE_ACHIEVEMENT_ENTERLIST = "TO_GUIDE_ACHIEVEMENT_ENTERLIST";

    public const string TO_GUIDE_FAVORABILITY_PHONE_EVENT_GOBACK_COERCE = "TO_GUIDE_FAVORABILITY_PHONE_EVENT_GOBACK_COERCE";//好感度手机事件返回后强制
    public const string TO_GUIDE_FAVORABILITY_PHONE_EVENT_OVER = "TO_GUIDE_FAVORABILITY_PHONE_EVENT_OVER";//好感度手机事件强制引导结束

    public const string TO_GUIDE_HIDE_MAINLIENGUIDEVIEW = "TO_GUIDE_HIDE_MAINLIENGUIDEVIEW";
    public const string GUIDE_TO_TAKEPHOTOSGAME_STARTGAME = "GUIDE_TO_TAKEPHOTOSGAME_STARTGAME";

    //Download  扩展下载领取奖励
    public const string CMD_DOWNLOAD_OK = "CMD_DOWNLOAD_OK";
    public const string CMD_HIDEVIEW = "CMD_HIDEVIEW";
    
    
    //星活动
    public const string CMD_STAR_ACTIVITY_TOGGLE_SELECT_DAY = "CMD_STAR_ACTIVITY_TOGGLE_SELECT_DAY";  //星活动Toggle选择的天数
    public const string CMD_STAR_ACTIVITY_ACTIVE_REWARD = "CMD_STAR_ACTIVITY_ACTIVE_REWARD";//星活动的活跃奖励
    public const string CMD_STAR_ACTIVITY_SHOW_TOPBAR_AND_BACKBTN = "CMD_STAR_ACTIVITY_SHOW_TOPBAR_AND_BACKBTN";//
    
    //Guide MainLine
    public const string CMD_MIANLINE_GUIDE_SHOW_TOPBAR_AND_BACKBTN = "CMD_MIANLINE_GUIDE_SHOW_TOPBAR_AND_BACKBTN";//主线引导活动奖励是否显示topBar和返回btn
    public const string CMD_MIANLINE_GUIDE_PHONE_TO_MAINLINE = "CMD_MIANLINE_GUIDE_PHONE_TO_MAINLINE";//手机短息读完去主线
    public const string CMD_PLAYER_BIRTHDAY_TOGGLE_SELECT_DAY = "CMD_PLAYER_BIRTHDAY_TOGGLE_SELECT_DAY";  //生日活动Toggle选择的天数
    public const string CMD_PLAYER_BIRTHDAY_ACTIVE_REWARD = "CMD_PLAYER_BIRTHDAY_ACTIVE_REWARD";//
   
    
    //ActivityTemplate
    public const string CMD_ACTIVITYTEMPLATE1_ON_GETBTN = "CMD_ACTIVITYTEMPLATE1_ON_GETBTN";//活动模板1（国庆活动）点击获取Btn
    public const string CMD_ACTIVITYTEMPLATE1_ON_LOTTERBTN = "CMD_ACTIVITYTEMPLATE1_ON_LOTTERBTN";//活动模板1（国庆活动）点击抽奖Btn
    public const string CMD_ACTIVITYTEMPLATE1_ON_PREVIEWBTN = "CMD_ACTIVITYTEMPLATE1_ON_PREVIEWBTN";//活动模板1（国庆活动）点击奖励一览Btn
    public const string CMD_ACTIVITYTEMPLATE1_ACTIVITY_OVER = "CMD_ACTIVITYTEMPLATE1_ACTIVITY_OVER";//活动模板1（国庆活动）活动结束

    public const string CMD_ACTIVITYTEMPLATE1_GET_ACTIVE_AWARD = "CMD_ACTIVITYTEMPLATE1_GET_ACTIVE_AWARD";//活动模板1（国庆活动）领取活跃奖励
    public const string CMD_ACTIVITYTEMPLATE1_ON_SHOW_REFRESH = "CMD_ACTIVITYTEMPLATE1_ON_SHOW_REFRESH"; //活动模板1（在显示刷新）
    public const string CMD_ACTIVITYTEMPLATE1_ACTIVITY_SHOW_TOPBAR_AND_BACKBTN = "CMD_ACTIVITYTEMPLATE1_ACTIVITY_SHOW_TOPBAR_AND_BACKBTN";

    public const string CMD_ACTIVITYTEMPLATE1_ON_LEFT_BTN = "CMD_ACTIVITYTEMPLATE1_ON_LEFT_BTN";//活动模板1（国庆活动）左边按钮
    public const string CMD_ACTIVITYTEMPLATE1_ON_RIGHT_BTN = "CMD_ACTIVITYTEMPLATE1_ON_RIGHT_BTN";//活动模板1（国庆活动）右边按钮

    //ActivityLotteryTemplate
    public const string CMD_ACTIVITY_LOTTERY_TEMPLATE1_ON_LOTTERY_BTN = "CMD_ACTIVITY_LOTTERY_TEMPLATE1_ON_LOTTERY_BTN";//活动摇奖模板点击进入星盘Btn
    public const string MODULE_ACTIVITY_CAPSULE_TEMPLATE_COPY_BTN = "MODULE_ACTIVITY_CAPSULE_TEMPLATE_COPY_BTN";//活动摇奖模板副本按钮

    public const string CMD_ACTIVITY_CAPSULE_TEMPLATE_OPEN_STORY_WINDOW = "CMD_ACTIVITY_CAPSULE_TEMPLATE_OPEN_STORY_WINDOW";//活动摇奖模板打开剧情弹窗
    public const string MODULE_ACTIVITY_CAPSULE_TEMPLATE_OPEN_MAIN_PANEL = "MODULE_ACTIVITY_CAPSULE_TEMPLATE_OPEN_MAIN_PANEL";//活动摇奖模板打开主界面
    public const string MODULE_ACTIVITY_CAPSULE_TEMPLATE_OPEN_DRAW_PANEL = "MODULE_ACTIVITY_CAPSULE_TEMPLATE_OPEN_DRAW_PANEL";//活动摇奖模板打开星盘界面
    public const string MODULE_ACTIVITY_CAPSULE_TEMPLATE_Hide_BACKBTN = "MODULE_ACTIVITY_CAPSULE_TEMPLATE_Hide_BACKBTN";//活动摇奖模板隐藏返回按钮

    public const string MODULE_ACTIVITY_CAPSULE_TEMPLATE_ACTIVITY_OVER = "MODULE_ACTIVITY_CAPSULE_TEMPLATE_ACTIVITY_OVER";//活动摇奖模板活动结束

    //生日
    public const string CMD_PLAYERBITTHDAY_SHOW_TOPBAR_AND_BACKBTN = "CMD_PLAYERBITTHDAY_SHOW_TOPBAR_AND_BACKBTN";

    //首充
    public const string CMD_FIRSTRECHARGE_HIDE_BACK_BTN = "CMD_FIRSTRECHARGE_HIDE_BACK_BTN";
    
    //扭蛋战斗
    public const string CMD_CAPSULEBATTLE_FINISH = "CMD_CAPSULEBATTLE_FINISH"; //扭蛋活动战斗完成
    public const string CMD_CAPSULEBATTLE_ITEM_DATA = "CMD_CAPSULEBATTLE_ITEM_DATA";//扭蛋战斗道具Date
    public const string CMD_CAPSULEBATTLE_NEXT = "CMD_CAPSULEBATTLE_NEXT";//扭蛋战斗下一步
    public const string CMD_CAPSULEBATTLE_SHOW_REWARD = "CMD_CAPSULEBATTLE_SHOW_REWARD";//扭蛋战斗显示战斗结束奖励
    public const string CMD_CAPSULEBATTLE_CHOOSE_LEVEL = "CMD_CAPSULEBATTLE_CHOOSE_LEVEL";//扭蛋战斗选择关卡

    public const string CMD_CAPSULEBATTLE_SHOW_SUPPORTER_POWER = "CMD_CAPSULEBATTLE_SHOW_SUPPORTER_POWER";
    public const string CMD_CAPSULEBATTLE_SHOW_SUPPORTER_VIEW = "CMD_CAPSULEBATTLE_SHOW_SUPPORTER_VIEW";
    public const string CMD_CAPSULEBATTLE_HIDE_PROGRESS = "CMD_CAPSULEBATTLE_HIDE_PROGRESS"; //开始放过场动画时要隐藏进度
    public const string CMD_CAPSULEBATTLE_FANS_CALL_ANIMATION_FINISH = "CMD_CAPSULEBATTLE_FANS_CALL_ANIMATION_FINISH";
    public const string CMD_CAPSULEBATTLE_SECOND_SHOW_FANS = "CMD_CAPSULEBATTLE_SECOND_SHOW_FANS";
    public const string CMD_CAPSULEBATTLE_CHANGE_POWER = "CMD_CAPSULEBATTLE_CHANGE_POWER";
    public const string CMD_CAPSULEBATTLE_SET_POWER = "CMD_CAPSULEBATTLE_SET_POWER";
    public const string CMD_CAPSULEBATTLE_SUPERSTAR_CONFIRM = "CMD_CAPSULEBATTLE_SUPERSTAR_CONFIRM";
    public const string CMD_CAPSULEBATTLE_SEND_ROLE_ID = "CMD_CAPSULEBATTLE_SEND_ROLE_ID";
    public const string CMD_CAPSULEBATTLE_GET_RES = "CMD_CAPSULEBATTLE_GET_RES";
    public const string CMD_CAPSULEBATTLE_SHOW_FAIL = "CMD_CAPSULEBATTLE_SHOW_FAIL";
    public const string CMD_CAPSULEBATTLE_RESULT_DATA = "CMD_CAPSULEBATTLE_RESULT_DATA";
    public const string CMD_CAPSULEBATTLE_SHOW_BATTLE_WIN_ANIMATION = "CMD_CAPSULEBATTLE_SHOW_BATTLE_WIN_ANIMATION";
    
    
    //音乐模板
    public const string CMD_ACTIVITY_MUSIC_TEMPLATE_ON_SHOW_REFRESH = "CMD_ACTIVITY_MUSIC_TEMPLATE_ON_SHOW_REFRESH";//音乐模板OnShow刷新      
    public const string CMD_OPEN_ACTIVITYMUSIC_EXCHANGESHOP = "CMD_OPEN_ACTIVITYMUSIC_EXCHANGESHOP";  //进入兑换商店模板
    public const string CMD_SHOW_ACTIVITYMUSIC_EXCHANGESHOP = "CMD_SHOW_ACTIVITYMUSIC_EXCHANGESHOP";
    public const string CMD_ACTIVITY_MUSCI_BACK_EXCHANGESHOP = "CMD_ACTIVITY_MUSCI_BACK_EXCHANGESHOP"; //退出音游兑换商店界面
    public const string CMD_OPEN_ACTIVITYMUSIC_TASK_WINDOW = "CMD_OPEN_ACTIVITYMUSIC_TASK_WINDOW";   //打开音游任务窗口
    public const string CMD_OPEN_ACTIVITYMUSIC_STORY_WINDOW = "CMD_OPEN_ACTIVITYMUSIC_STORY_WINDOW";//打开音游剧情窗口
    public const string CMD_ACTIVITY_MUSIC_OVER = "CMD_ACTIVITY_MUSIC_OVER";//音游活动结束
    
    //哄睡
    public const string CMD_COAXSLEEP_GOTO_CUR_PLAYER = "CMD_COAXSLEEP_GOTO_CUR_PLAYER";   //哄睡去往当前哪个男主
    public const string CMD_COAXSLEEP_OPEN_ANI = "CMD_COAXSLEEP_OPEN_ANI";//哄睡打开试听界面
    public const string CMD_COAXSLEEP_PLAY_OVER = "CMD_COAXSLEEP_PLAY_OVER";//哄睡试听界面结束
    public const string CMD_CPAXSLEEP_DESTROY_PANEL = "CMD_CPAXSLEEP_DESTROY_PANEL"; //摧毁当前界面
    public const string CMD_CPAXSLEEP_SHOW_ON_PLAY_PANEL = "CMD_CPAXSLEEP_SHOW_ON_PLAY_PANEL";//显示播放音频界面
    public const string CMD_GUIDE_COAXSLEEP_TOW_STAGE = "CMD_GUIDE_COAXSLEEP_TOW_STAGE";//哄睡二阶段引导
    

}