// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from base.proto</summary>
public static partial class BaseReflection {

  #region Descriptor
  /// <summary>File descriptor for base.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static BaseReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgpiYXNlLnByb3RvKiIKCENyZWRpdFBCEgcKA1NTUhAAEgYKAlNSEAESBQoB",
          "UhACKlAKBlN0YXJQQhIKCgZTVEFSXzAQABIKCgZTVEFSXzEQARIKCgZTVEFS",
          "XzIQAhIKCgZTVEFSXzMQAxIKCgZTVEFSXzQQBBIKCgZTVEFSXzUQBSpOCghQ",
          "bGF5ZXJQQhIICgROT05FEAASEAoMVEFOR19ZSV9DSEVOEAESDgoKUUlOX1lV",
          "X1pIRRACEgoKBllBTl9KSRADEgoKBkNISV9ZVRAEKjkKC0V2b2x1dGlvblBC",
          "EgkKBUVWT18wEAASCQoFRVZPXzEQARIJCgVFVk9fMhACEgkKBUVWT18zEAMq",
          "RAoKRHJhd1R5cGVQQhIKCgZCWV9HRU0QABINCglCWV9HRU1fMTAQARILCgdC",
          "WV9HT0xEEAISDgoKQllfR09MRF8xMBADKq4BCgpSZXNvdXJjZVBCEggKBENB",
          "UkQQABIICgRJVEVNEAESCgoGUFVaWkxFEAISCQoFUE9XRVIQAxIHCgNHRU0Q",
          "BBIICgRHT0xEEAUSCAoERkFOUxAGEgcKA0VYUBAHEhMKD0VOQ09VUkFHRV9Q",
          "T1dFUhAIEhAKDEZBVk9SQUJJTElUWRAJEgwKCE1FTU9SSUVTEAoSCwoHRUxF",
          "TUVOVBALEg0KCVNJR05BVFVSRRAMKloKEERlcGFydG1lbnRUeXBlUEISCwoH",
          "U1VQUE9SVBAAEgoKBkFDVElWRRABEg0KCUZJTkFOQ0lBTBACEgwKCFJFU09V",
          "UkNFEAMSEAoMVFJBTlNNSVNTSU9OEAQqIwoLTGV2ZWxUeXBlUEISCQoFVkFM",
          "VUUQABIJCgVTVE9SWRABKmEKCUFiaWxpdHlQQhILCgdTSU5HSU5HEAASCwoH",
          "REFOQ0lORxABEg0KCUNPTVBPU0lORxACEg4KClBPUFVMQVJJVFkQAxIJCgVD",
          "SEFSTRAEEhAKDFBFUlNFVkVSQU5DRRAFKkQKDFBob25lTW9kbGVQQhIHCgNN",
          "U0cQABIICgRDQUxMEAESEQoNRlJJRU5EX0NJUkNMRRACEg4KCk1JQ1JPX0JM",
          "T0cQAypQCgtEcmF3RXZlbnRQQhIMCghHRU1fQkFTRRAAEgoKBkdFTV9TUhAB",
          "EgsKB0dFTV9TU1IQAhINCglHT0xEX0JBU0UQAxILCgdHT0xEX1NSEAQqQgoN",
          "SXRlbUV4cFR5cGVQQhINCglUWVBFX05PTkUQABITCg9UWVBFX0RFUEFSVE1F",
          "TlQQARINCglUWVBFX0NBUkQQAiqHAQoNTWlzc2lvblR5cGVQQhIJCgVEQUlM",
          "WRAAEg4KCldFRUtfREFJTFkQARIICgRTSUdOEAISDwoLU1RBUl9DT1VSU0UQ",
          "AxITCg9TVEFSUllfQ09WRU5BTlQQBBISCg5DSElfWVVfTUlTU0lPThAFEhcK",
          "E05FV19TVEFSUllfQ09WRU5BTlQQBipbCg9NaXNzaW9uU3RhdHVzUEISFQoR",
          "U1RBVFVTX1VORklOSVNIRUQQABIUChBTVEFUVVNfVU5DTEFJTUVEEAESGwoX",
          "U1RBVFVTX0JFX1JFV0FSREVEX1dJVEgQAio3CgpHYW1lVHlwZVBCEgwKCE9S",
          "RElOQVJZEAASDQoJRElGRklDVUxUEAESDAoIVklTSVRJTkcQCioxCg9MZXZl",
          "bFBsb3RUeXBlUEISDQoJUExPVF9GQU5TEAASDwoLUExPVF9QTEFZRVIQASpE",
          "CgxCdXlHZW1UeXBlUEISDAoIQlVZX0dPTEQQABINCglCVVlfUE9XRVIQARIX",
          "ChNCVVlfRU5DT1VSQUdFX1BPV0VSEAIquwMKDkFjdGl2aXR5VHlwZVBCEhgK",
          "FEFDVElWSVRZX1RFTl9EQVlfU0lHEAASGgoWQUNUSVZJVFlfU0VWRU5fREFZ",
          "X1NJRxABEhYKEkFDVElWSVRZX1BPV0VSX0dFVBACEhcKE0FDVElWSVRZX01P",
          "TlRIX1NJR04QAxIYChRBQ1RJVklUWV9HUk9XVEhfRlVORBAEEhcKE0FDVElW",
          "SVRZX01PTlRIX0NBUkQQBRIXChNBQ1RJVklUWV9EQUlMWV9HSUZUEAYSIAoc",
          "QUNUSVZJVFlfTU9OVEhfQ0FSRF9SRUNIQVJHRRAHEiAKHEFDVElWSVRZX0ZB",
          "Q0VfQk9PS19BVFRFTlRJT04QCBIYChRBQ1RJVklUWV9ERUxFVEVfVEVTVBAJ",
          "EhoKFkFDVElWSVRZX0RSQVdfVEVNUExBVEUQChIiCh5BQ1RJVklUWV9BQ0NV",
          "TVVMQVRJVkVfUkVDSEFSR0UQCxIdChlBQ1RJVklUWV9DQVBTVUxFX1RFTVBM",
          "QVRFEAwSIAocQUNUSVZJVFlfRFJBV19URU5fQ09OVElOVU9VUxANEhcKE0FD",
          "VElWSVRZX01VU0lDX0dBTUUQDipJChVNZW1vcmllc0NvbnN1bWVUeXBlUEIS",
          "FgoSTUVNT1JJRVNfQlVZX1BPV0VSEAASGAoUTUVNT1JJRVNfUkVTRUxBVF9O",
          "VU0QASqIAQoNRWxlbWVudFR5cGVQQhIMCghURU1QTEFURRAAEgkKBUxBQkVM",
          "EAESCQoFSU1BR0UQAhIOCgpURVhUX1NUWUxFEAMSCgoGUkFDS0VUEAQSBgoC",
          "QkcQBRIICgRURVhUEAYSCQoFU09VTkQQBxIKCgZBVkFUQVIQCBIOCgpBVkFU",
          "QVJfQk9YEAkqNAoPRWxlbWVudE1vZHVsZVBCEgkKBURJQVJZEAASCQoFQ0xP",
          "Q0sQARILCgdJTlNUQUxMEAIqNgoNRHJlc3NVcFR5cGVQQhIQCgxUWVBFX0NM",
          "T1RIRVMQABITCg9UWVBFX0JBQ0tHUk9VTkQQASomCgtNb25leVR5cGVQQhIL",
          "CgdNT19HT0xEEAASCgoGTU9fR0VNEAEqgQEKC0d1aWRlVHlwZVBCEg4KCk1B",
          "SU5fR1VJREUQABIXChNFTkNPVVJBR0VfQUNUX0dVSURFEAESFwoTQ0FSRF9N",
          "RU1PUklFU19HVUlERRACEhUKEU1BSU5fR1VJREVfUkVDT1JEEAMSGQoVTE9W",
          "RV9HVUlERV9DT0FYX1NMRUVQEAQqSgoPQ29tbW9kaXR5VHlwZVBCEgwKCFJF",
          "Q0hBUkdFEAASDgoKTU9OVEhfQ0FSRBABEggKBEdJRlQQAhIPCgtHUk9XVEhf",
          "RlVORBADKqsBCgtNYWxsTGFiZWxQQhIQCgxMQUJFTF9DT01NT04QABIWChJM",
          "QUJFTF9CRVNUX1NFTExFUlMQARIQCgxMQUJFTF9OT1ZJQ0UQAhINCglMQUJF",
          "TF9WSVAQAxIOCgpMQUJFTF9TVEFSEAQSFAoQTEFCRUxfREFJTFlfR0lGVBAF",
          "EhYKEkxBQkVMX1RSSUdHRVJfR0lGVBAGEhMKD0xBQkVMX1JFU09VUkNFUxAH",
          "KmgKCk1hbGxTb3J0UEISEQoNTUFMTF9PUkRJTkFSWRAAEg0KCU1BTExfR0lG",
          "VBABEg0KCU1BTExfSVRFTRACEhMKD01BTExfQkFUQ0hfSVRFTRADEhQKEE1B",
          "TExfUkVCQVRFX0dJRlQQBCo7CgpNYWxsVHlwZVBCEg0KCU1BbGxfR09MRBAA",
          "EgwKCE1BbGxfR0VNEAESEAoMTUFMTF9ERUZBVUxUEAIq2gEKFk9wdGlvbmFs",
          "QWN0aXZpdHlUeXBlUEISGgoWT1BUSU9OQUxfU0VWRU5fREFZX1NJRxAAEhcK",
          "E09QVElPTkFMX0ZJUlNUX1JVU0gQARIZChVPUFRJT05BTF9NT05USExZX0NB",
          "UkQQAhIVChFPUFRJT05BTF9ET1dOTE9BRBADEiAKHE9QVElPTkFMX0ZBQ0Vf",
          "Qk9PS19BVFRFTlRJT04QBBIgChxPUFRJT05BTF9DSEFOTkVMX1JFU0VSVkFU",
          "SU9OEAUSFQoRT1BUSU9OQUxfVkVSSUZJRUQQBiowCgtTaGFyZVR5cGVQQhIO",
          "CgpTSEFSRV9EUkFXEAASEQoNU0hBUkVfQ0xPVEhFUxABKlcKDU9yZGVyU3Rh",
          "dHVzUEISEAoMU1RBVFVTX1NUQVJUEAASEAoMU1RBVFVTX0ZJSVNIEAESDwoL",
          "U1RBVFVTX0JBQ0sQAhIRCg1TVEFUVVNfT0ZGU0VUEAMqPQoRQWN0aXZpdHlF",
          "bmRUeXBlUEISDAoIRU5EX0xPTkcQABIMCghFTkRfUlVMRRABEgwKCEVORF9V",
          "U0VSEAIqTgoSRmlyc3RQcml6ZVN0YXR1c1BCEhMKD0ZQX05PVF9JTlZPTFZF",
          "RBAAEg8KC0ZQX1JFQ0VJVkVEEAESEgoORlBfVU5BQ0NBTElNRUQQAio6CgxS",
          "ZWZyZXNoRGF5UEISFwoTUkVGUkVTSF9FVkVSTEFTVElORxAAEhEKDVJFRlJF",
          "U0hfREFJTFkQASo+Cg5EcmF3UG9vbFR5cGVQQhIUChBEUkFXX1BPT0xfQ09N",
          "TU9OEAASFgoSRFJBV19QT09MX0FDVElWSVRZEAEqOQoTTXVzaWNHYW1lRGlm",
          "ZlR5cGVQQhIJCgVFTlRSWRAAEgkKBUJBU0lTEAESDAoIQURWQU5DRUQQAio1",
          "ChJBdWRpb3NVbmxvY2tUeXBlUEISDgoKVU5MT0NLX0dFTRAAEg8KC1VOTE9D",
          "S19QTE9UEAFCLQofbmV0LmdhbGFzcG9ydHMuYmlnc3Rhci5wcm90b2NvbEIK",
          "QmFzZVByb3Rvc2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::CreditPB), typeof(global::StarPB), typeof(global::PlayerPB), typeof(global::EvolutionPB), typeof(global::DrawTypePB), typeof(global::ResourcePB), typeof(global::DepartmentTypePB), typeof(global::LevelTypePB), typeof(global::AbilityPB), typeof(global::PhoneModlePB), typeof(global::DrawEventPB), typeof(global::ItemExpTypePB), typeof(global::MissionTypePB), typeof(global::MissionStatusPB), typeof(global::GameTypePB), typeof(global::LevelPlotTypePB), typeof(global::BuyGemTypePB), typeof(global::ActivityTypePB), typeof(global::MemoriesConsumeTypePB), typeof(global::ElementTypePB), typeof(global::ElementModulePB), typeof(global::DressUpTypePB), typeof(global::MoneyTypePB), typeof(global::GuideTypePB), typeof(global::CommodityTypePB), typeof(global::MallLabelPB), typeof(global::MallSortPB), typeof(global::MallTypePB), typeof(global::OptionalActivityTypePB), typeof(global::ShareTypePB), typeof(global::OrderStatusPB), typeof(global::ActivityEndTypePB), typeof(global::FirstPrizeStatusPB), typeof(global::RefreshDayPB), typeof(global::DrawPoolTypePB), typeof(global::MusicGameDiffTypePB), typeof(global::AudiosUnlockTypePB), }, null));
  }
  #endregion

}
#region Enums
public enum CreditPB {
  [pbr::OriginalName("SSR")] Ssr = 0,
  [pbr::OriginalName("SR")] Sr = 1,
  [pbr::OriginalName("R")] R = 2,
}

public enum StarPB {
  [pbr::OriginalName("STAR_0")] Star0 = 0,
  [pbr::OriginalName("STAR_1")] Star1 = 1,
  [pbr::OriginalName("STAR_2")] Star2 = 2,
  [pbr::OriginalName("STAR_3")] Star3 = 3,
  [pbr::OriginalName("STAR_4")] Star4 = 4,
  [pbr::OriginalName("STAR_5")] Star5 = 5,
}

public enum PlayerPB {
  [pbr::OriginalName("NONE")] None = 0,
  [pbr::OriginalName("TANG_YI_CHEN")] TangYiChen = 1,
  [pbr::OriginalName("QIN_YU_ZHE")] QinYuZhe = 2,
  [pbr::OriginalName("YAN_JI")] YanJi = 3,
  [pbr::OriginalName("CHI_YU")] ChiYu = 4,
}

public enum EvolutionPB {
  [pbr::OriginalName("EVO_0")] Evo0 = 0,
  [pbr::OriginalName("EVO_1")] Evo1 = 1,
  [pbr::OriginalName("EVO_2")] Evo2 = 2,
  [pbr::OriginalName("EVO_3")] Evo3 = 3,
}

public enum DrawTypePB {
  [pbr::OriginalName("BY_GEM")] ByGem = 0,
  [pbr::OriginalName("BY_GEM_10")] ByGem10 = 1,
  [pbr::OriginalName("BY_GOLD")] ByGold = 2,
  [pbr::OriginalName("BY_GOLD_10")] ByGold10 = 3,
}

public enum ResourcePB {
  [pbr::OriginalName("CARD")] Card = 0,
  [pbr::OriginalName("ITEM")] Item = 1,
  [pbr::OriginalName("PUZZLE")] Puzzle = 2,
  [pbr::OriginalName("POWER")] Power = 3,
  [pbr::OriginalName("GEM")] Gem = 4,
  [pbr::OriginalName("GOLD")] Gold = 5,
  [pbr::OriginalName("FANS")] Fans = 6,
  /// <summary>
  ///应援会经验
  /// </summary>
  [pbr::OriginalName("EXP")] Exp = 7,
  /// <summary>
  ///应援活动体力
  /// </summary>
  [pbr::OriginalName("ENCOURAGE_POWER")] EncouragePower = 8,
  /// <summary>
  ///好感度
  /// </summary>
  [pbr::OriginalName("FAVORABILITY")] Favorability = 9,
  /// <summary>
  ///星缘回忆体力
  /// </summary>
  [pbr::OriginalName("MEMORIES")] Memories = 10,
  /// <summary>
  ///特殊元素（日记、闹钟等）
  /// </summary>
  [pbr::OriginalName("ELEMENT")] Element = 11,
  /// <summary>
  ///签名
  /// </summary>
  [pbr::OriginalName("SIGNATURE")] Signature = 12,
}

public enum DepartmentTypePB {
  /// <summary>
  ///* 应援 
  /// </summary>
  [pbr::OriginalName("SUPPORT")] Support = 0,
  /// <summary>
  ///* 活跃 
  /// </summary>
  [pbr::OriginalName("ACTIVE")] Active = 1,
  /// <summary>
  ///* 财力 
  /// </summary>
  [pbr::OriginalName("FINANCIAL")] Financial = 2,
  /// <summary>
  ///* 资源 
  /// </summary>
  [pbr::OriginalName("RESOURCE")] Resource = 3,
  /// <summary>
  ///* 传播力 
  /// </summary>
  [pbr::OriginalName("TRANSMISSION")] Transmission = 4,
}

public enum LevelTypePB {
  [pbr::OriginalName("VALUE")] Value = 0,
  [pbr::OriginalName("STORY")] Story = 1,
}

public enum AbilityPB {
  [pbr::OriginalName("SINGING")] Singing = 0,
  [pbr::OriginalName("DANCING")] Dancing = 1,
  [pbr::OriginalName("COMPOSING")] Composing = 2,
  [pbr::OriginalName("POPULARITY")] Popularity = 3,
  [pbr::OriginalName("CHARM")] Charm = 4,
  [pbr::OriginalName("PERSEVERANCE")] Perseverance = 5,
}

public enum PhoneModlePB {
  /// <summary>
  ///短信
  /// </summary>
  [pbr::OriginalName("MSG")] Msg = 0,
  /// <summary>
  ///电话
  /// </summary>
  [pbr::OriginalName("CALL")] Call = 1,
  /// <summary>
  ///朋友圈
  /// </summary>
  [pbr::OriginalName("FRIEND_CIRCLE")] FriendCircle = 2,
  /// <summary>
  ///微博
  /// </summary>
  [pbr::OriginalName("MICRO_BLOG")] MicroBlog = 3,
}

public enum DrawEventPB {
  /// <summary>
  ///宝石基础事件 
  /// </summary>
  [pbr::OriginalName("GEM_BASE")] GemBase = 0,
  /// <summary>
  ///宝石sr事件
  /// </summary>
  [pbr::OriginalName("GEM_SR")] GemSr = 1,
  /// <summary>
  ///宝石ssr事件
  /// </summary>
  [pbr::OriginalName("GEM_SSR")] GemSsr = 2,
  /// <summary>
  ///金币基数
  /// </summary>
  [pbr::OriginalName("GOLD_BASE")] GoldBase = 3,
  /// <summary>
  ///金币sr事件 
  /// </summary>
  [pbr::OriginalName("GOLD_SR")] GoldSr = 4,
}

public enum ItemExpTypePB {
  /// <summary>
  ///无
  /// </summary>
  [pbr::OriginalName("TYPE_NONE")] TypeNone = 0,
  /// <summary>
  ///应援会
  /// </summary>
  [pbr::OriginalName("TYPE_DEPARTMENT")] TypeDepartment = 1,
  /// <summary>
  ///卡牌升级
  /// </summary>
  [pbr::OriginalName("TYPE_CARD")] TypeCard = 2,
}

public enum MissionTypePB {
  /// <summary>
  ///日常任务
  /// </summary>
  [pbr::OriginalName("DAILY")] Daily = 0,
  /// <summary>
  ///周常任务
  /// </summary>
  [pbr::OriginalName("WEEK_DAILY")] WeekDaily = 1,
  /// <summary>
  ///签到
  /// </summary>
  [pbr::OriginalName("SIGN")] Sign = 2,
  /// <summary>
  ///星路历程
  /// </summary>
  [pbr::OriginalName("STAR_COURSE")] StarCourse = 3,
  /// <summary>
  ///星动之约
  /// </summary>
  [pbr::OriginalName("STARRY_COVENANT")] StarryCovenant = 4,
  /// <summary>
  ///迟郁生日任务
  /// </summary>
  [pbr::OriginalName("CHI_YU_MISSION")] ChiYuMission = 5,
  /// <summary>
  ///新的星动之约
  /// </summary>
  [pbr::OriginalName("NEW_STARRY_COVENANT")] NewStarryCovenant = 6,
}

public enum MissionStatusPB {
  /// <summary>
  ///未完成
  /// </summary>
  [pbr::OriginalName("STATUS_UNFINISHED")] StatusUnfinished = 0,
  /// <summary>
  ///未领取
  /// </summary>
  [pbr::OriginalName("STATUS_UNCLAIMED")] StatusUnclaimed = 1,
  /// <summary>
  ///已领取
  /// </summary>
  [pbr::OriginalName("STATUS_BE_REWARDED_WITH")] StatusBeRewardedWith = 2,
}

public enum GameTypePB {
  /// <summary>
  ///普通
  /// </summary>
  [pbr::OriginalName("ORDINARY")] Ordinary = 0,
  /// <summary>
  ///困难
  /// </summary>
  [pbr::OriginalName("DIFFICULT")] Difficult = 1,
  /// <summary>
  ///探班
  /// </summary>
  [pbr::OriginalName("VISITING")] Visiting = 10,
}

public enum LevelPlotTypePB {
  /// <summary>
  ///粉丝
  /// </summary>
  [pbr::OriginalName("PLOT_FANS")] PlotFans = 0,
  /// <summary>
  ///男主
  /// </summary>
  [pbr::OriginalName("PLOT_PLAYER")] PlotPlayer = 1,
}

public enum BuyGemTypePB {
  /// <summary>
  ///购买金币
  /// </summary>
  [pbr::OriginalName("BUY_GOLD")] BuyGold = 0,
  /// <summary>
  ///购买体力
  /// </summary>
  [pbr::OriginalName("BUY_POWER")] BuyPower = 1,
  /// <summary>
  ///购买应援活动体力
  /// </summary>
  [pbr::OriginalName("BUY_ENCOURAGE_POWER")] BuyEncouragePower = 2,
}

public enum ActivityTypePB {
  /// <summary>
  ///十天签到
  /// </summary>
  [pbr::OriginalName("ACTIVITY_TEN_DAY_SIG")] ActivityTenDaySig = 0,
  /// <summary>
  ///七天累计签到
  /// </summary>
  [pbr::OriginalName("ACTIVITY_SEVEN_DAY_SIG")] ActivitySevenDaySig = 1,
  /// <summary>
  ///每日体力领取
  /// </summary>
  [pbr::OriginalName("ACTIVITY_POWER_GET")] ActivityPowerGet = 2,
  /// <summary>
  ///月签到
  /// </summary>
  [pbr::OriginalName("ACTIVITY_MONTH_SIGN")] ActivityMonthSign = 3,
  /// <summary>
  ///成长基金
  /// </summary>
  [pbr::OriginalName("ACTIVITY_GROWTH_FUND")] ActivityGrowthFund = 4,
  /// <summary>
  ///月卡
  /// </summary>
  [pbr::OriginalName("ACTIVITY_MONTH_CARD")] ActivityMonthCard = 5,
  /// <summary>
  ///每日礼包
  /// </summary>
  [pbr::OriginalName("ACTIVITY_DAILY_GIFT")] ActivityDailyGift = 6,
  /// <summary>
  ///月卡充值
  /// </summary>
  [pbr::OriginalName("ACTIVITY_MONTH_CARD_RECHARGE")] ActivityMonthCardRecharge = 7,
  /// <summary>
  ///脸书关注
  /// </summary>
  [pbr::OriginalName("ACTIVITY_FACE_BOOK_ATTENTION")] ActivityFaceBookAttention = 8,
  /// <summary>
  ///删测福利规则
  /// </summary>
  [pbr::OriginalName("ACTIVITY_DELETE_TEST")] ActivityDeleteTest = 9,
  /// <summary>
  ///抽奖活动模板
  /// </summary>
  [pbr::OriginalName("ACTIVITY_DRAW_TEMPLATE")] ActivityDrawTemplate = 10,
  /// <summary>
  ///累计充值
  /// </summary>
  [pbr::OriginalName("ACTIVITY_ACCUMULATIVE_RECHARGE")] ActivityAccumulativeRecharge = 11,
  /// <summary>
  ///扭蛋活动模板
  /// </summary>
  [pbr::OriginalName("ACTIVITY_CAPSULE_TEMPLATE")] ActivityCapsuleTemplate = 12,
  /// <summary>
  ///抽卡十连活动
  /// </summary>
  [pbr::OriginalName("ACTIVITY_DRAW_TEN_CONTINUOUS")] ActivityDrawTenContinuous = 13,
  /// <summary>
  ///音游活动
  /// </summary>
  [pbr::OriginalName("ACTIVITY_MUSIC_GAME")] ActivityMusicGame = 14,
}

public enum MemoriesConsumeTypePB {
  /// <summary>
  ///星缘回忆体力购买
  /// </summary>
  [pbr::OriginalName("MEMORIES_BUY_POWER")] MemoriesBuyPower = 0,
  /// <summary>
  ///星缘回忆重置次数
  /// </summary>
  [pbr::OriginalName("MEMORIES_RESELAT_NUM")] MemoriesReselatNum = 1,
}

/// <summary>
///素材类型
/// </summary>
public enum ElementTypePB {
  /// <summary>
  ///模板
  /// </summary>
  [pbr::OriginalName("TEMPLATE")] Template = 0,
  /// <summary>
  ///标签
  /// </summary>
  [pbr::OriginalName("LABEL")] Label = 1,
  /// <summary>
  ///贴纸
  /// </summary>
  [pbr::OriginalName("IMAGE")] Image = 2,
  /// <summary>
  ///字体
  /// </summary>
  [pbr::OriginalName("TEXT_STYLE")] TextStyle = 3,
  /// <summary>
  ///拍立得
  /// </summary>
  [pbr::OriginalName("RACKET")] Racket = 4,
  /// <summary>
  ///背景
  /// </summary>
  [pbr::OriginalName("BG")] Bg = 5,
  /// <summary>
  ///文本框
  /// </summary>
  [pbr::OriginalName("TEXT")] Text = 6,
  /// <summary>
  ///语音
  /// </summary>
  [pbr::OriginalName("SOUND")] Sound = 7,
  /// <summary>
  ///头像
  /// </summary>
  [pbr::OriginalName("AVATAR")] Avatar = 8,
  /// <summary>
  ///头像框
  /// </summary>
  [pbr::OriginalName("AVATAR_BOX")] AvatarBox = 9,
}

/// <summary>
///素材应用的模块
/// </summary>
public enum ElementModulePB {
  /// <summary>
  ///日记
  /// </summary>
  [pbr::OriginalName("DIARY")] Diary = 0,
  /// <summary>
  ///闹钟
  /// </summary>
  [pbr::OriginalName("CLOCK")] Clock = 1,
  /// <summary>
  ///设置
  /// </summary>
  [pbr::OriginalName("INSTALL")] Install = 2,
}

public enum DressUpTypePB {
  /// <summary>
  ///服装
  /// </summary>
  [pbr::OriginalName("TYPE_CLOTHES")] TypeClothes = 0,
  /// <summary>
  ///背景
  /// </summary>
  [pbr::OriginalName("TYPE_BACKGROUND")] TypeBackground = 1,
}

public enum MoneyTypePB {
  /// <summary>
  ///金币
  /// </summary>
  [pbr::OriginalName("MO_GOLD")] MoGold = 0,
  /// <summary>
  ///宝石
  /// </summary>
  [pbr::OriginalName("MO_GEM")] MoGem = 1,
}

public enum GuideTypePB {
  /// <summary>
  ///主线
  /// </summary>
  [pbr::OriginalName("MAIN_GUIDE")] MainGuide = 0,
  /// <summary>
  ///应援会
  /// </summary>
  [pbr::OriginalName("ENCOURAGE_ACT_GUIDE")] EncourageActGuide = 1,
  /// <summary>
  ///星缘回忆
  /// </summary>
  [pbr::OriginalName("CARD_MEMORIES_GUIDE")] CardMemoriesGuide = 2,
  /// <summary>
  ///新手引导记录
  /// </summary>
  [pbr::OriginalName("MAIN_GUIDE_RECORD")] MainGuideRecord = 3,
  /// <summary>
  ///哄睡引导记录
  /// </summary>
  [pbr::OriginalName("LOVE_GUIDE_COAX_SLEEP")] LoveGuideCoaxSleep = 4,
}

public enum CommodityTypePB {
  /// <summary>
  ///充值宝石
  /// </summary>
  [pbr::OriginalName("RECHARGE")] Recharge = 0,
  /// <summary>
  ///月卡
  /// </summary>
  [pbr::OriginalName("MONTH_CARD")] MonthCard = 1,
  /// <summary>
  ///礼包
  /// </summary>
  [pbr::OriginalName("GIFT")] Gift = 2,
  /// <summary>
  ///成长基金
  /// </summary>
  [pbr::OriginalName("GROWTH_FUND")] GrowthFund = 3,
}

public enum MallLabelPB {
  /// <summary>
  ///常规
  /// </summary>
  [pbr::OriginalName("LABEL_COMMON")] LabelCommon = 0,
  /// <summary>
  ///热卖页签
  /// </summary>
  [pbr::OriginalName("LABEL_BEST_SELLERS")] LabelBestSellers = 1,
  /// <summary>
  ///新手页签
  /// </summary>
  [pbr::OriginalName("LABEL_NOVICE")] LabelNovice = 2,
  /// <summary>
  ///VIP特权
  /// </summary>
  [pbr::OriginalName("LABEL_VIP")] LabelVip = 3,
  /// <summary>
  ///星缘
  /// </summary>
  [pbr::OriginalName("LABEL_STAR")] LabelStar = 4,
  /// <summary>
  ///每日礼包页签
  /// </summary>
  [pbr::OriginalName("LABEL_DAILY_GIFT")] LabelDailyGift = 5,
  /// <summary>
  ///触发礼包页签
  /// </summary>
  [pbr::OriginalName("LABEL_TRIGGER_GIFT")] LabelTriggerGift = 6,
  /// <summary>
  ///资源站
  /// </summary>
  [pbr::OriginalName("LABEL_RESOURCES")] LabelResources = 7,
}

public enum MallSortPB {
  /// <summary>
  ///普通
  /// </summary>
  [pbr::OriginalName("MALL_ORDINARY")] MallOrdinary = 0,
  /// <summary>
  ///礼包
  /// </summary>
  [pbr::OriginalName("MALL_GIFT")] MallGift = 1,
  /// <summary>
  ///道具
  /// </summary>
  [pbr::OriginalName("MALL_ITEM")] MallItem = 2,
  /// <summary>
  ///批量道具
  /// </summary>
  [pbr::OriginalName("MALL_BATCH_ITEM")] MallBatchItem = 3,
  /// <summary>
  ///返利礼包
  /// </summary>
  [pbr::OriginalName("MALL_REBATE_GIFT")] MallRebateGift = 4,
}

public enum MallTypePB {
  /// <summary>
  ///金币商品
  /// </summary>
  [pbr::OriginalName("MAll_GOLD")] MallGold = 0,
  /// <summary>
  ///钻石商品
  /// </summary>
  [pbr::OriginalName("MAll_GEM")] MallGem = 1,
  /// <summary>
  ///默认商品
  /// </summary>
  [pbr::OriginalName("MALL_DEFAULT")] MallDefault = 2,
}

public enum OptionalActivityTypePB {
  /// <summary>
  ///七天累计签到
  /// </summary>
  [pbr::OriginalName("OPTIONAL_SEVEN_DAY_SIG")] OptionalSevenDaySig = 0,
  /// <summary>
  ///首冲活动
  /// </summary>
  [pbr::OriginalName("OPTIONAL_FIRST_RUSH")] OptionalFirstRush = 1,
  /// <summary>
  ///月卡每天领取
  /// </summary>
  [pbr::OriginalName("OPTIONAL_MONTHLY_CARD")] OptionalMonthlyCard = 2,
  /// <summary>
  ///下载领取
  /// </summary>
  [pbr::OriginalName("OPTIONAL_DOWNLOAD")] OptionalDownload = 3,
  /// <summary>
  ///不要脸书关注
  /// </summary>
  [pbr::OriginalName("OPTIONAL_FACE_BOOK_ATTENTION")] OptionalFaceBookAttention = 4,
  /// <summary>
  ///渠道登录奖励
  /// </summary>
  [pbr::OriginalName("OPTIONAL_CHANNEL_RESERVATION")] OptionalChannelReservation = 5,
  /// <summary>
  ///实名认证奖励
  /// </summary>
  [pbr::OriginalName("OPTIONAL_VERIFIED")] OptionalVerified = 6,
}

public enum ShareTypePB {
  /// <summary>
  ///抽卡
  /// </summary>
  [pbr::OriginalName("SHARE_DRAW")] ShareDraw = 0,
  /// <summary>
  ///服装
  /// </summary>
  [pbr::OriginalName("SHARE_CLOTHES")] ShareClothes = 1,
}

public enum OrderStatusPB {
  /// <summary>
  ///充值失败
  /// </summary>
  [pbr::OriginalName("STATUS_START")] StatusStart = 0,
  /// <summary>
  ///充值成功
  /// </summary>
  [pbr::OriginalName("STATUS_FIISH")] StatusFiish = 1,
  /// <summary>
  ///退单状态
  /// </summary>
  [pbr::OriginalName("STATUS_BACK")] StatusBack = 2,
  /// <summary>
  ///充值异常。补偿等额宝石
  /// </summary>
  [pbr::OriginalName("STATUS_OFFSET")] StatusOffset = 3,
}

public enum ActivityEndTypePB {
  /// <summary>
  ///永久
  /// </summary>
  [pbr::OriginalName("END_LONG")] EndLong = 0,
  /// <summary>
  ///根据规则
  /// </summary>
  [pbr::OriginalName("END_RULE")] EndRule = 1,
  /// <summary>
  ///根据玩家
  /// </summary>
  [pbr::OriginalName("END_USER")] EndUser = 2,
}

public enum FirstPrizeStatusPB {
  /// <summary>
  ///未参加
  /// </summary>
  [pbr::OriginalName("FP_NOT_INVOLVED")] FpNotInvolved = 0,
  /// <summary>
  ///已领取
  /// </summary>
  [pbr::OriginalName("FP_RECEIVED")] FpReceived = 1,
  /// <summary>
  ///未领取
  /// </summary>
  [pbr::OriginalName("FP_UNACCALIMED")] FpUnaccalimed = 2,
}

public enum RefreshDayPB {
  /// <summary>
  ///永久
  /// </summary>
  [pbr::OriginalName("REFRESH_EVERLASTING")] RefreshEverlasting = 0,
  /// <summary>
  ///每天
  /// </summary>
  [pbr::OriginalName("REFRESH_DAILY")] RefreshDaily = 1,
}

public enum DrawPoolTypePB {
  /// <summary>
  ///普通抽卡
  /// </summary>
  [pbr::OriginalName("DRAW_POOL_COMMON")] DrawPoolCommon = 0,
  /// <summary>
  ///活动抽卡
  /// </summary>
  [pbr::OriginalName("DRAW_POOL_ACTIVITY")] DrawPoolActivity = 1,
}

public enum MusicGameDiffTypePB {
  /// <summary>
  ///入门
  /// </summary>
  [pbr::OriginalName("ENTRY")] Entry = 0,
  /// <summary>
  ///基础
  /// </summary>
  [pbr::OriginalName("BASIS")] Basis = 1,
  /// <summary>
  ///进阶
  /// </summary>
  [pbr::OriginalName("ADVANCED")] Advanced = 2,
}

public enum AudiosUnlockTypePB {
  /// <summary>
  ///宝石解锁
  /// </summary>
  [pbr::OriginalName("UNLOCK_GEM")] UnlockGem = 0,
  /// <summary>
  ///剧情解锁
  /// </summary>
  [pbr::OriginalName("UNLOCK_PLOT")] UnlockPlot = 1,
}

#endregion


#endregion Designer generated code
