// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bean_rmb_mall_rule.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Proto {

  /// <summary>Holder for reflection information generated from bean_rmb_mall_rule.proto</summary>
  public static partial class BeanRmbMallRuleReflection {

    #region Descriptor
    /// <summary>File descriptor for bean_rmb_mall_rule.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BeanRmbMallRuleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhiZWFuX3JtYl9tYWxsX3J1bGUucHJvdG8SCWNvbS5wcm90bxoKYmFzZS5w",
            "cm90bxoQYmVhbl9hd2FyZC5wcm90byKZAwoNUm1iTWFsbFJ1bGVQQhIPCgdt",
            "YWxsX2lkGAEgASgREigKDmNvbW1vZGl0eV90eXBlGAIgASgOMhAuQ29tbW9k",
            "aXR5VHlwZVBCEh4KCW1hbGxfc29ydBgDIAEoDjILLk1hbGxTb3J0UEISEQoJ",
            "bWFsbF9uYW1lGAQgASgJEhEKCW1hbGxfZGVzYxgFIAEoCRISCgpnaWZ0X2lt",
            "YWdlGAYgASgJEgwKBHNsb3QYByABKBESIAoKbWFsbF9sYWJlbBgIIAEoDjIM",
            "Lk1hbGxMYWJlbFBCEhMKC2xhYmVsX2ltYWdlGAkgASgJEhIKCnJlYWxfcHJp",
            "Y2UYCiABKBESFgoOb3JpZ2luYWxfcHJpY2UYCyABKBESDwoHYnV5X21heBgM",
            "IAEoERIXCg9idXlfcmVmcmVzaF9kYXkYDSABKBESIQoFYXdhcmQYDiADKAsy",
            "Ei5jb20ucHJvdG8uQXdhcmRQQhISCgpzdGFydF90aW1lGA8gASgSEhAKCGVu",
            "ZF90aW1lGBAgASgSEg8KB3NwZWNpYWwYESABKAhCNAofbmV0LmdhbGFzcG9y",
            "dHMuYmlnc3Rhci5wcm90b2NvbEIRUm1iTWFsbFJ1bGVQcm90b3NiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::BaseReflection.Descriptor, global::Com.Proto.BeanAwardReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.RmbMallRulePB), global::Com.Proto.RmbMallRulePB.Parser, new[]{ "MallId", "CommodityType", "MallSort", "MallName", "MallDesc", "GiftImage", "Slot", "MallLabel", "LabelImage", "RealPrice", "OriginalPrice", "BuyMax", "BuyRefreshDay", "Award", "StartTime", "EndTime", "Special" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///AwardPB Award
  /// </summary>
  public sealed partial class RmbMallRulePB : pb::IMessage<RmbMallRulePB> {
    private static readonly pb::MessageParser<RmbMallRulePB> _parser = new pb::MessageParser<RmbMallRulePB>(() => new RmbMallRulePB());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RmbMallRulePB> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.BeanRmbMallRuleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RmbMallRulePB() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RmbMallRulePB(RmbMallRulePB other) : this() {
      mallId_ = other.mallId_;
      commodityType_ = other.commodityType_;
      mallSort_ = other.mallSort_;
      mallName_ = other.mallName_;
      mallDesc_ = other.mallDesc_;
      giftImage_ = other.giftImage_;
      slot_ = other.slot_;
      mallLabel_ = other.mallLabel_;
      labelImage_ = other.labelImage_;
      realPrice_ = other.realPrice_;
      originalPrice_ = other.originalPrice_;
      buyMax_ = other.buyMax_;
      buyRefreshDay_ = other.buyRefreshDay_;
      award_ = other.award_.Clone();
      startTime_ = other.startTime_;
      endTime_ = other.endTime_;
      special_ = other.special_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RmbMallRulePB Clone() {
      return new RmbMallRulePB(this);
    }

    /// <summary>Field number for the "mall_id" field.</summary>
    public const int MallIdFieldNumber = 1;
    private int mallId_;
    /// <summary>
    ///商品id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MallId {
      get { return mallId_; }
      set {
        mallId_ = value;
      }
    }

    /// <summary>Field number for the "commodity_type" field.</summary>
    public const int CommodityTypeFieldNumber = 2;
    private global::CommodityTypePB commodityType_ = 0;
    /// <summary>
    ///产品类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CommodityTypePB CommodityType {
      get { return commodityType_; }
      set {
        commodityType_ = value;
      }
    }

    /// <summary>Field number for the "mall_sort" field.</summary>
    public const int MallSortFieldNumber = 3;
    private global::MallSortPB mallSort_ = 0;
    /// <summary>
    ///商品分类
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MallSortPB MallSort {
      get { return mallSort_; }
      set {
        mallSort_ = value;
      }
    }

    /// <summary>Field number for the "mall_name" field.</summary>
    public const int MallNameFieldNumber = 4;
    private string mallName_ = "";
    /// <summary>
    ///商品名称
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MallName {
      get { return mallName_; }
      set {
        mallName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mall_desc" field.</summary>
    public const int MallDescFieldNumber = 5;
    private string mallDesc_ = "";
    /// <summary>
    ///商品描述
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MallDesc {
      get { return mallDesc_; }
      set {
        mallDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gift_image" field.</summary>
    public const int GiftImageFieldNumber = 6;
    private string giftImage_ = "";
    /// <summary>
    ///礼包图片
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string GiftImage {
      get { return giftImage_; }
      set {
        giftImage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "slot" field.</summary>
    public const int SlotFieldNumber = 7;
    private int slot_;
    /// <summary>
    ///槽位
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Slot {
      get { return slot_; }
      set {
        slot_ = value;
      }
    }

    /// <summary>Field number for the "mall_label" field.</summary>
    public const int MallLabelFieldNumber = 8;
    private global::MallLabelPB mallLabel_ = 0;
    /// <summary>
    ///商品标签
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MallLabelPB MallLabel {
      get { return mallLabel_; }
      set {
        mallLabel_ = value;
      }
    }

    /// <summary>Field number for the "label_image" field.</summary>
    public const int LabelImageFieldNumber = 9;
    private string labelImage_ = "";
    /// <summary>
    ///商品类型展示图片
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LabelImage {
      get { return labelImage_; }
      set {
        labelImage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "real_price" field.</summary>
    public const int RealPriceFieldNumber = 10;
    private int realPrice_;
    /// <summary>
    ///真实价格
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RealPrice {
      get { return realPrice_; }
      set {
        realPrice_ = value;
      }
    }

    /// <summary>Field number for the "original_price" field.</summary>
    public const int OriginalPriceFieldNumber = 11;
    private int originalPrice_;
    /// <summary>
    ///原价
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int OriginalPrice {
      get { return originalPrice_; }
      set {
        originalPrice_ = value;
      }
    }

    /// <summary>Field number for the "buy_max" field.</summary>
    public const int BuyMaxFieldNumber = 12;
    private int buyMax_;
    /// <summary>
    ///周期内购买上限
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BuyMax {
      get { return buyMax_; }
      set {
        buyMax_ = value;
      }
    }

    /// <summary>Field number for the "buy_refresh_day" field.</summary>
    public const int BuyRefreshDayFieldNumber = 13;
    private int buyRefreshDay_;
    /// <summary>
    ///商品次数刷新周期
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BuyRefreshDay {
      get { return buyRefreshDay_; }
      set {
        buyRefreshDay_ = value;
      }
    }

    /// <summary>Field number for the "award" field.</summary>
    public const int AwardFieldNumber = 14;
    private static readonly pb::FieldCodec<global::Com.Proto.AwardPB> _repeated_award_codec
        = pb::FieldCodec.ForMessage(114, global::Com.Proto.AwardPB.Parser);
    private readonly pbc::RepeatedField<global::Com.Proto.AwardPB> award_ = new pbc::RepeatedField<global::Com.Proto.AwardPB>();
    /// <summary>
    ///商品奖励内容
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Com.Proto.AwardPB> Award {
      get { return award_; }
    }

    /// <summary>Field number for the "start_time" field.</summary>
    public const int StartTimeFieldNumber = 15;
    private long startTime_;
    /// <summary>
    ///开始时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long StartTime {
      get { return startTime_; }
      set {
        startTime_ = value;
      }
    }

    /// <summary>Field number for the "end_time" field.</summary>
    public const int EndTimeFieldNumber = 16;
    private long endTime_;
    /// <summary>
    ///结束时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long EndTime {
      get { return endTime_; }
      set {
        endTime_ = value;
      }
    }

    /// <summary>Field number for the "special" field.</summary>
    public const int SpecialFieldNumber = 17;
    private bool special_;
    /// <summary>
    ///特殊展示礼包
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Special {
      get { return special_; }
      set {
        special_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RmbMallRulePB);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RmbMallRulePB other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MallId != other.MallId) return false;
      if (CommodityType != other.CommodityType) return false;
      if (MallSort != other.MallSort) return false;
      if (MallName != other.MallName) return false;
      if (MallDesc != other.MallDesc) return false;
      if (GiftImage != other.GiftImage) return false;
      if (Slot != other.Slot) return false;
      if (MallLabel != other.MallLabel) return false;
      if (LabelImage != other.LabelImage) return false;
      if (RealPrice != other.RealPrice) return false;
      if (OriginalPrice != other.OriginalPrice) return false;
      if (BuyMax != other.BuyMax) return false;
      if (BuyRefreshDay != other.BuyRefreshDay) return false;
      if(!award_.Equals(other.award_)) return false;
      if (StartTime != other.StartTime) return false;
      if (EndTime != other.EndTime) return false;
      if (Special != other.Special) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MallId != 0) hash ^= MallId.GetHashCode();
      if (CommodityType != 0) hash ^= CommodityType.GetHashCode();
      if (MallSort != 0) hash ^= MallSort.GetHashCode();
      if (MallName.Length != 0) hash ^= MallName.GetHashCode();
      if (MallDesc.Length != 0) hash ^= MallDesc.GetHashCode();
      if (GiftImage.Length != 0) hash ^= GiftImage.GetHashCode();
      if (Slot != 0) hash ^= Slot.GetHashCode();
      if (MallLabel != 0) hash ^= MallLabel.GetHashCode();
      if (LabelImage.Length != 0) hash ^= LabelImage.GetHashCode();
      if (RealPrice != 0) hash ^= RealPrice.GetHashCode();
      if (OriginalPrice != 0) hash ^= OriginalPrice.GetHashCode();
      if (BuyMax != 0) hash ^= BuyMax.GetHashCode();
      if (BuyRefreshDay != 0) hash ^= BuyRefreshDay.GetHashCode();
      hash ^= award_.GetHashCode();
      if (StartTime != 0L) hash ^= StartTime.GetHashCode();
      if (EndTime != 0L) hash ^= EndTime.GetHashCode();
      if (Special != false) hash ^= Special.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MallId != 0) {
        output.WriteRawTag(8);
        output.WriteSInt32(MallId);
      }
      if (CommodityType != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) CommodityType);
      }
      if (MallSort != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) MallSort);
      }
      if (MallName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(MallName);
      }
      if (MallDesc.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(MallDesc);
      }
      if (GiftImage.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(GiftImage);
      }
      if (Slot != 0) {
        output.WriteRawTag(56);
        output.WriteSInt32(Slot);
      }
      if (MallLabel != 0) {
        output.WriteRawTag(64);
        output.WriteEnum((int) MallLabel);
      }
      if (LabelImage.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(LabelImage);
      }
      if (RealPrice != 0) {
        output.WriteRawTag(80);
        output.WriteSInt32(RealPrice);
      }
      if (OriginalPrice != 0) {
        output.WriteRawTag(88);
        output.WriteSInt32(OriginalPrice);
      }
      if (BuyMax != 0) {
        output.WriteRawTag(96);
        output.WriteSInt32(BuyMax);
      }
      if (BuyRefreshDay != 0) {
        output.WriteRawTag(104);
        output.WriteSInt32(BuyRefreshDay);
      }
      award_.WriteTo(output, _repeated_award_codec);
      if (StartTime != 0L) {
        output.WriteRawTag(120);
        output.WriteSInt64(StartTime);
      }
      if (EndTime != 0L) {
        output.WriteRawTag(128, 1);
        output.WriteSInt64(EndTime);
      }
      if (Special != false) {
        output.WriteRawTag(136, 1);
        output.WriteBool(Special);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MallId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(MallId);
      }
      if (CommodityType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) CommodityType);
      }
      if (MallSort != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MallSort);
      }
      if (MallName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MallName);
      }
      if (MallDesc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MallDesc);
      }
      if (GiftImage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GiftImage);
      }
      if (Slot != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(Slot);
      }
      if (MallLabel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MallLabel);
      }
      if (LabelImage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LabelImage);
      }
      if (RealPrice != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(RealPrice);
      }
      if (OriginalPrice != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(OriginalPrice);
      }
      if (BuyMax != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(BuyMax);
      }
      if (BuyRefreshDay != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(BuyRefreshDay);
      }
      size += award_.CalculateSize(_repeated_award_codec);
      if (StartTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(StartTime);
      }
      if (EndTime != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeSInt64Size(EndTime);
      }
      if (Special != false) {
        size += 2 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RmbMallRulePB other) {
      if (other == null) {
        return;
      }
      if (other.MallId != 0) {
        MallId = other.MallId;
      }
      if (other.CommodityType != 0) {
        CommodityType = other.CommodityType;
      }
      if (other.MallSort != 0) {
        MallSort = other.MallSort;
      }
      if (other.MallName.Length != 0) {
        MallName = other.MallName;
      }
      if (other.MallDesc.Length != 0) {
        MallDesc = other.MallDesc;
      }
      if (other.GiftImage.Length != 0) {
        GiftImage = other.GiftImage;
      }
      if (other.Slot != 0) {
        Slot = other.Slot;
      }
      if (other.MallLabel != 0) {
        MallLabel = other.MallLabel;
      }
      if (other.LabelImage.Length != 0) {
        LabelImage = other.LabelImage;
      }
      if (other.RealPrice != 0) {
        RealPrice = other.RealPrice;
      }
      if (other.OriginalPrice != 0) {
        OriginalPrice = other.OriginalPrice;
      }
      if (other.BuyMax != 0) {
        BuyMax = other.BuyMax;
      }
      if (other.BuyRefreshDay != 0) {
        BuyRefreshDay = other.BuyRefreshDay;
      }
      award_.Add(other.award_);
      if (other.StartTime != 0L) {
        StartTime = other.StartTime;
      }
      if (other.EndTime != 0L) {
        EndTime = other.EndTime;
      }
      if (other.Special != false) {
        Special = other.Special;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            MallId = input.ReadSInt32();
            break;
          }
          case 16: {
            commodityType_ = (global::CommodityTypePB) input.ReadEnum();
            break;
          }
          case 24: {
            mallSort_ = (global::MallSortPB) input.ReadEnum();
            break;
          }
          case 34: {
            MallName = input.ReadString();
            break;
          }
          case 42: {
            MallDesc = input.ReadString();
            break;
          }
          case 50: {
            GiftImage = input.ReadString();
            break;
          }
          case 56: {
            Slot = input.ReadSInt32();
            break;
          }
          case 64: {
            mallLabel_ = (global::MallLabelPB) input.ReadEnum();
            break;
          }
          case 74: {
            LabelImage = input.ReadString();
            break;
          }
          case 80: {
            RealPrice = input.ReadSInt32();
            break;
          }
          case 88: {
            OriginalPrice = input.ReadSInt32();
            break;
          }
          case 96: {
            BuyMax = input.ReadSInt32();
            break;
          }
          case 104: {
            BuyRefreshDay = input.ReadSInt32();
            break;
          }
          case 114: {
            award_.AddEntriesFrom(input, _repeated_award_codec);
            break;
          }
          case 120: {
            StartTime = input.ReadSInt64();
            break;
          }
          case 128: {
            EndTime = input.ReadSInt64();
            break;
          }
          case 136: {
            Special = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
