// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bean_activity_mission_rule.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Proto {

  /// <summary>Holder for reflection information generated from bean_activity_mission_rule.proto</summary>
  public static partial class BeanActivityMissionRuleReflection {

    #region Descriptor
    /// <summary>File descriptor for bean_activity_mission_rule.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BeanActivityMissionRuleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBiZWFuX2FjdGl2aXR5X21pc3Npb25fcnVsZS5wcm90bxIJY29tLnByb3Rv",
            "GgpiYXNlLnByb3RvGhBiZWFuX2F3YXJkLnByb3RvGhdiZWFuX21pc3Npb25f",
            "cnVsZS5wcm90byLjAQoVQWN0aXZpdHlNaXNzaW9uUnVsZVBCEhsKE2FjdGl2",
            "aXR5X21pc3Npb25faWQYASABKBESHQoVYWN0aXZpdHlfbWlzc2lvbl9uYW1l",
            "GAIgASgJEhMKC2FjdGl2aXR5X2lkGAMgASgREiEKBWF3YXJkGAQgAygLMhIu",
            "Y29tLnByb3RvLkF3YXJkUEISHQoVYWN0aXZpdHlfbWlzc2lvbl9kZXNjGAUg",
            "ASgJEg8KB2p1bXBfdG8YBiABKAkSJgoFZXh0cmEYByABKAsyFy5jb20ucHJv",
            "dG8uRXh0cmFWYWx1ZVBCQjwKH25ldC5nYWxhc3BvcnRzLmJpZ3N0YXIucHJv",
            "dG9jb2xCGUFjdGl2aXR5TWlzc2lvblJ1bGVQcm90b3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::BaseReflection.Descriptor, global::Com.Proto.BeanAwardReflection.Descriptor, global::Com.Proto.BeanMissionRuleReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.ActivityMissionRulePB), global::Com.Proto.ActivityMissionRulePB.Parser, new[]{ "ActivityMissionId", "ActivityMissionName", "ActivityId", "Award", "ActivityMissionDesc", "JumpTo", "Extra" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///ActivityMissionRulePB ActivityMissionRule
  /// </summary>
  public sealed partial class ActivityMissionRulePB : pb::IMessage<ActivityMissionRulePB> {
    private static readonly pb::MessageParser<ActivityMissionRulePB> _parser = new pb::MessageParser<ActivityMissionRulePB>(() => new ActivityMissionRulePB());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ActivityMissionRulePB> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.BeanActivityMissionRuleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActivityMissionRulePB() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActivityMissionRulePB(ActivityMissionRulePB other) : this() {
      activityMissionId_ = other.activityMissionId_;
      activityMissionName_ = other.activityMissionName_;
      activityId_ = other.activityId_;
      award_ = other.award_.Clone();
      activityMissionDesc_ = other.activityMissionDesc_;
      jumpTo_ = other.jumpTo_;
      Extra = other.extra_ != null ? other.Extra.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActivityMissionRulePB Clone() {
      return new ActivityMissionRulePB(this);
    }

    /// <summary>Field number for the "activity_mission_id" field.</summary>
    public const int ActivityMissionIdFieldNumber = 1;
    private int activityMissionId_;
    /// <summary>
    ///活动任务序号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ActivityMissionId {
      get { return activityMissionId_; }
      set {
        activityMissionId_ = value;
      }
    }

    /// <summary>Field number for the "activity_mission_name" field.</summary>
    public const int ActivityMissionNameFieldNumber = 2;
    private string activityMissionName_ = "";
    /// <summary>
    ///活动任务名称
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ActivityMissionName {
      get { return activityMissionName_; }
      set {
        activityMissionName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "activity_id" field.</summary>
    public const int ActivityIdFieldNumber = 3;
    private int activityId_;
    /// <summary>
    ///活动任务类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ActivityId {
      get { return activityId_; }
      set {
        activityId_ = value;
      }
    }

    /// <summary>Field number for the "award" field.</summary>
    public const int AwardFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Com.Proto.AwardPB> _repeated_award_codec
        = pb::FieldCodec.ForMessage(34, global::Com.Proto.AwardPB.Parser);
    private readonly pbc::RepeatedField<global::Com.Proto.AwardPB> award_ = new pbc::RepeatedField<global::Com.Proto.AwardPB>();
    /// <summary>
    ///奖励
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Com.Proto.AwardPB> Award {
      get { return award_; }
    }

    /// <summary>Field number for the "activity_mission_desc" field.</summary>
    public const int ActivityMissionDescFieldNumber = 5;
    private string activityMissionDesc_ = "";
    /// <summary>
    ///活动任务描述
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ActivityMissionDesc {
      get { return activityMissionDesc_; }
      set {
        activityMissionDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "jump_to" field.</summary>
    public const int JumpToFieldNumber = 6;
    private string jumpTo_ = "";
    /// <summary>
    ///跳转链接
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string JumpTo {
      get { return jumpTo_; }
      set {
        jumpTo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "extra" field.</summary>
    public const int ExtraFieldNumber = 7;
    private global::Com.Proto.ExtraValuePB extra_;
    /// <summary>
    ///额外参数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Proto.ExtraValuePB Extra {
      get { return extra_; }
      set {
        extra_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ActivityMissionRulePB);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ActivityMissionRulePB other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ActivityMissionId != other.ActivityMissionId) return false;
      if (ActivityMissionName != other.ActivityMissionName) return false;
      if (ActivityId != other.ActivityId) return false;
      if(!award_.Equals(other.award_)) return false;
      if (ActivityMissionDesc != other.ActivityMissionDesc) return false;
      if (JumpTo != other.JumpTo) return false;
      if (!object.Equals(Extra, other.Extra)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ActivityMissionId != 0) hash ^= ActivityMissionId.GetHashCode();
      if (ActivityMissionName.Length != 0) hash ^= ActivityMissionName.GetHashCode();
      if (ActivityId != 0) hash ^= ActivityId.GetHashCode();
      hash ^= award_.GetHashCode();
      if (ActivityMissionDesc.Length != 0) hash ^= ActivityMissionDesc.GetHashCode();
      if (JumpTo.Length != 0) hash ^= JumpTo.GetHashCode();
      if (extra_ != null) hash ^= Extra.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ActivityMissionId != 0) {
        output.WriteRawTag(8);
        output.WriteSInt32(ActivityMissionId);
      }
      if (ActivityMissionName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ActivityMissionName);
      }
      if (ActivityId != 0) {
        output.WriteRawTag(24);
        output.WriteSInt32(ActivityId);
      }
      award_.WriteTo(output, _repeated_award_codec);
      if (ActivityMissionDesc.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ActivityMissionDesc);
      }
      if (JumpTo.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(JumpTo);
      }
      if (extra_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Extra);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ActivityMissionId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(ActivityMissionId);
      }
      if (ActivityMissionName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ActivityMissionName);
      }
      if (ActivityId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(ActivityId);
      }
      size += award_.CalculateSize(_repeated_award_codec);
      if (ActivityMissionDesc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ActivityMissionDesc);
      }
      if (JumpTo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(JumpTo);
      }
      if (extra_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Extra);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ActivityMissionRulePB other) {
      if (other == null) {
        return;
      }
      if (other.ActivityMissionId != 0) {
        ActivityMissionId = other.ActivityMissionId;
      }
      if (other.ActivityMissionName.Length != 0) {
        ActivityMissionName = other.ActivityMissionName;
      }
      if (other.ActivityId != 0) {
        ActivityId = other.ActivityId;
      }
      award_.Add(other.award_);
      if (other.ActivityMissionDesc.Length != 0) {
        ActivityMissionDesc = other.ActivityMissionDesc;
      }
      if (other.JumpTo.Length != 0) {
        JumpTo = other.JumpTo;
      }
      if (other.extra_ != null) {
        if (extra_ == null) {
          extra_ = new global::Com.Proto.ExtraValuePB();
        }
        Extra.MergeFrom(other.Extra);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ActivityMissionId = input.ReadSInt32();
            break;
          }
          case 18: {
            ActivityMissionName = input.ReadString();
            break;
          }
          case 24: {
            ActivityId = input.ReadSInt32();
            break;
          }
          case 34: {
            award_.AddEntriesFrom(input, _repeated_award_codec);
            break;
          }
          case 42: {
            ActivityMissionDesc = input.ReadString();
            break;
          }
          case 50: {
            JumpTo = input.ReadString();
            break;
          }
          case 58: {
            if (extra_ == null) {
              extra_ = new global::Com.Proto.ExtraValuePB();
            }
            input.ReadMessage(extra_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
