// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bean_card_resolve_rule.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Proto {

  /// <summary>Holder for reflection information generated from bean_card_resolve_rule.proto</summary>
  public static partial class BeanCardResolveRuleReflection {

    #region Descriptor
    /// <summary>File descriptor for bean_card_resolve_rule.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BeanCardResolveRuleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxiZWFuX2NhcmRfcmVzb2x2ZV9ydWxlLnByb3RvEgljb20ucHJvdG8aCmJh",
            "c2UucHJvdG8iqwIKEUNhcmRSZXNvbHZlUnVsZVBCEhkKBnBsYXllchgBIAEo",
            "DjIJLlBsYXllclBCEhkKBmNyZWRpdBgCIAEoDjIJLkNyZWRpdFBCEjoKB3Jl",
            "c29sdmUYAyADKAsyKS5jb20ucHJvdG8uQ2FyZFJlc29sdmVSdWxlUEIuUmVz",
            "b2x2ZUVudHJ5EkEKC2V2b19yZXNvbHZlGAQgAygLMiwuY29tLnByb3RvLkNh",
            "cmRSZXNvbHZlUnVsZVBCLkV2b1Jlc29sdmVFbnRyeRouCgxSZXNvbHZlRW50",
            "cnkSCwoDa2V5GAEgASgREg0KBXZhbHVlGAIgASgROgI4ARoxCg9Fdm9SZXNv",
            "bHZlRW50cnkSCwoDa2V5GAEgASgREg0KBXZhbHVlGAIgASgROgI4AUI4Ch9u",
            "ZXQuZ2FsYXNwb3J0cy5iaWdzdGFyLnByb3RvY29sQhVDYXJkUmVzb2x2ZVJ1",
            "bGVQcm90b3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::BaseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.CardResolveRulePB), global::Com.Proto.CardResolveRulePB.Parser, new[]{ "Player", "Credit", "Resolve", "EvoResolve" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///CardResolveRulePB CardResolveRule
  /// </summary>
  public sealed partial class CardResolveRulePB : pb::IMessage<CardResolveRulePB> {
    private static readonly pb::MessageParser<CardResolveRulePB> _parser = new pb::MessageParser<CardResolveRulePB>(() => new CardResolveRulePB());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CardResolveRulePB> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.BeanCardResolveRuleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CardResolveRulePB() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CardResolveRulePB(CardResolveRulePB other) : this() {
      player_ = other.player_;
      credit_ = other.credit_;
      resolve_ = other.resolve_.Clone();
      evoResolve_ = other.evoResolve_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CardResolveRulePB Clone() {
      return new CardResolveRulePB(this);
    }

    /// <summary>Field number for the "player" field.</summary>
    public const int PlayerFieldNumber = 1;
    private global::PlayerPB player_ = 0;
    /// <summary>
    ///男主类型1-4
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::PlayerPB Player {
      get { return player_; }
      set {
        player_ = value;
      }
    }

    /// <summary>Field number for the "credit" field.</summary>
    public const int CreditFieldNumber = 2;
    private global::CreditPB credit_ = 0;
    /// <summary>
    ///稀有度0-2
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CreditPB Credit {
      get { return credit_; }
      set {
        credit_ = value;
      }
    }

    /// <summary>Field number for the "resolve" field.</summary>
    public const int ResolveFieldNumber = 3;
    private static readonly pbc::MapField<int, int>.Codec _map_resolve_codec
        = new pbc::MapField<int, int>.Codec(pb::FieldCodec.ForSInt32(8), pb::FieldCodec.ForSInt32(16), 26);
    private readonly pbc::MapField<int, int> resolve_ = new pbc::MapField<int, int>();
    /// <summary>
    ///分解获得的道具
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, int> Resolve {
      get { return resolve_; }
    }

    /// <summary>Field number for the "evo_resolve" field.</summary>
    public const int EvoResolveFieldNumber = 4;
    private static readonly pbc::MapField<int, int>.Codec _map_evoResolve_codec
        = new pbc::MapField<int, int>.Codec(pb::FieldCodec.ForSInt32(8), pb::FieldCodec.ForSInt32(16), 34);
    private readonly pbc::MapField<int, int> evoResolve_ = new pbc::MapField<int, int>();
    /// <summary>
    ///进化抵消的道具
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, int> EvoResolve {
      get { return evoResolve_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CardResolveRulePB);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CardResolveRulePB other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Player != other.Player) return false;
      if (Credit != other.Credit) return false;
      if (!Resolve.Equals(other.Resolve)) return false;
      if (!EvoResolve.Equals(other.EvoResolve)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Player != 0) hash ^= Player.GetHashCode();
      if (Credit != 0) hash ^= Credit.GetHashCode();
      hash ^= Resolve.GetHashCode();
      hash ^= EvoResolve.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Player != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Player);
      }
      if (Credit != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Credit);
      }
      resolve_.WriteTo(output, _map_resolve_codec);
      evoResolve_.WriteTo(output, _map_evoResolve_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Player != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Player);
      }
      if (Credit != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Credit);
      }
      size += resolve_.CalculateSize(_map_resolve_codec);
      size += evoResolve_.CalculateSize(_map_evoResolve_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CardResolveRulePB other) {
      if (other == null) {
        return;
      }
      if (other.Player != 0) {
        Player = other.Player;
      }
      if (other.Credit != 0) {
        Credit = other.Credit;
      }
      resolve_.Add(other.resolve_);
      evoResolve_.Add(other.evoResolve_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            player_ = (global::PlayerPB) input.ReadEnum();
            break;
          }
          case 16: {
            credit_ = (global::CreditPB) input.ReadEnum();
            break;
          }
          case 26: {
            resolve_.AddEntriesFrom(input, _map_resolve_codec);
            break;
          }
          case 34: {
            evoResolve_.AddEntriesFrom(input, _map_evoResolve_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
