// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bean_user_draw.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Proto {

  /// <summary>Holder for reflection information generated from bean_user_draw.proto</summary>
  public static partial class BeanUserDrawReflection {

    #region Descriptor
    /// <summary>File descriptor for bean_user_draw.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BeanUserDrawReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRiZWFuX3VzZXJfZHJhdy5wcm90bxIJY29tLnByb3RvGgpiYXNlLnByb3Rv",
            "InwKClVzZXJEcmF3UEISDwoHdXNlcl9pZBgBIAEoERInCg5kcmF3X3Bvb2xf",
            "dHlwZRgCIAEoDjIPLkRyYXdQb29sVHlwZVBCEh4KCWRyYXdfdHlwZRgDIAEo",
            "DjILLkRyYXdUeXBlUEISFAoMcmVmcmVzaF90aW1lGAQgASgSQjEKH25ldC5n",
            "YWxhc3BvcnRzLmJpZ3N0YXIucHJvdG9jb2xCDlVzZXJEcmF3UHJvdG9zYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::BaseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Proto.UserDrawPB), global::Com.Proto.UserDrawPB.Parser, new[]{ "UserId", "DrawPoolType", "DrawType", "RefreshTime" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///UserPB User
  /// </summary>
  public sealed partial class UserDrawPB : pb::IMessage<UserDrawPB> {
    private static readonly pb::MessageParser<UserDrawPB> _parser = new pb::MessageParser<UserDrawPB>(() => new UserDrawPB());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UserDrawPB> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Proto.BeanUserDrawReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserDrawPB() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserDrawPB(UserDrawPB other) : this() {
      userId_ = other.userId_;
      drawPoolType_ = other.drawPoolType_;
      drawType_ = other.drawType_;
      refreshTime_ = other.refreshTime_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserDrawPB Clone() {
      return new UserDrawPB(this);
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 1;
    private int userId_;
    /// <summary>
    ///用户id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    /// <summary>Field number for the "draw_pool_type" field.</summary>
    public const int DrawPoolTypeFieldNumber = 2;
    private global::DrawPoolTypePB drawPoolType_ = 0;
    /// <summary>
    ///星盘类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DrawPoolTypePB DrawPoolType {
      get { return drawPoolType_; }
      set {
        drawPoolType_ = value;
      }
    }

    /// <summary>Field number for the "draw_type" field.</summary>
    public const int DrawTypeFieldNumber = 3;
    private global::DrawTypePB drawType_ = 0;
    /// <summary>
    ///抽奖事件
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DrawTypePB DrawType {
      get { return drawType_; }
      set {
        drawType_ = value;
      }
    }

    /// <summary>Field number for the "refresh_time" field.</summary>
    public const int RefreshTimeFieldNumber = 4;
    private long refreshTime_;
    /// <summary>
    ///免费刷新时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long RefreshTime {
      get { return refreshTime_; }
      set {
        refreshTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UserDrawPB);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UserDrawPB other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      if (DrawPoolType != other.DrawPoolType) return false;
      if (DrawType != other.DrawType) return false;
      if (RefreshTime != other.RefreshTime) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UserId != 0) hash ^= UserId.GetHashCode();
      if (DrawPoolType != 0) hash ^= DrawPoolType.GetHashCode();
      if (DrawType != 0) hash ^= DrawType.GetHashCode();
      if (RefreshTime != 0L) hash ^= RefreshTime.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UserId != 0) {
        output.WriteRawTag(8);
        output.WriteSInt32(UserId);
      }
      if (DrawPoolType != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) DrawPoolType);
      }
      if (DrawType != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) DrawType);
      }
      if (RefreshTime != 0L) {
        output.WriteRawTag(32);
        output.WriteSInt64(RefreshTime);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UserId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(UserId);
      }
      if (DrawPoolType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DrawPoolType);
      }
      if (DrawType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DrawType);
      }
      if (RefreshTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(RefreshTime);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UserDrawPB other) {
      if (other == null) {
        return;
      }
      if (other.UserId != 0) {
        UserId = other.UserId;
      }
      if (other.DrawPoolType != 0) {
        DrawPoolType = other.DrawPoolType;
      }
      if (other.DrawType != 0) {
        DrawType = other.DrawType;
      }
      if (other.RefreshTime != 0L) {
        RefreshTime = other.RefreshTime;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            UserId = input.ReadSInt32();
            break;
          }
          case 16: {
            drawPoolType_ = (global::DrawPoolTypePB) input.ReadEnum();
            break;
          }
          case 24: {
            drawType_ = (global::DrawTypePB) input.ReadEnum();
            break;
          }
          case 32: {
            RefreshTime = input.ReadSInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
